'use strict';

let unvrslCheckinCache={at:0,data:null};
function checkinToday(){return typeof iso==='function'?iso(new Date()):new Date().toISOString().slice(0,10)}
function checkinScore(c){if(!c)return null;return Math.round(((+c.sleep||3)+(+c.energy||3)+(+c.appetite||3)+(6-(+c.stress||3))+(6-(+c.soreness||3)))/25*100)}
function checkinSignal(c){const s=checkinScore(c);if(s==null)return{label:'Нет данных',cls:''};if(s<50)return{label:'Нужно внимание',cls:'orange'};if(s<68)return{label:'Восстановление ↓',cls:'orange'};return{label:'Всё нормально',cls:'green'}}
function checkinRating(id,label,left,right,value=3){return `<div class="readiness-item"><b><span>${label}</span><span id="${id}Val">${value}</span></b><input id="${id}" type="range" min="1" max="5" value="${value}" step="1" oninput="document.getElementById('${id}Val').textContent=this.value"><div class="row between muted small"><span>${left}</span><span>${right}</span></div></div>`}
async function loadMyCheckin(force=false){if(!cloud?.user||!cloud?.client)return null;if(!force&&Date.now()-unvrslCheckinCache.at<30000)return unvrslCheckinCache.data;const r=await cloud.client.from('checkins').select('*').eq('user_id',cloud.user.id).order('checkin_date',{ascending:false}).limit(1).maybeSingle();if(!r.error){unvrslCheckinCache={at:Date.now(),data:r.data||null};return r.data||null}return null}
async function openWeeklyCheckin(){if(!cloud?.user)return cloudAccountSheet();const prev=await loadMyCheckin(true),today=checkinToday(),same=prev?.checkin_date===today,c=same?prev:null;modal(`<div class="sheet-grabber"></div><h2>${same?'Чек-ин за сегодня':'Еженедельный чек-ин'}</h2><div class="muted">Сон, восстановление, вес и короткий комментарий. Обхваты ведутся отдельно в профиле.</div><div class="field"><label>Вес, кг</label><input id="ciWeight" type="number" inputmode="decimal" step="0.1" value="${c?.weight_kg??(typeof latestW==='function'?(latestW()??''):'')}" placeholder="Например, 82.4"></div><div class="readiness-grid">${checkinRating('ciSleep','Сон','Плохо','Отлично',c?.sleep||3)}${checkinRating('ciEnergy','Энергия','Низкая','Высокая',c?.energy||3)}${checkinRating('ciStress','Стресс','Низкий','Высокий',c?.stress||3)}${checkinRating('ciSore','Крепатура','Нет','Сильная',c?.soreness||3)}${checkinRating('ciAppetite','Аппетит','Низкий','Высокий',c?.appetite||3)}</div><div class="field"><label>Комментарий</label><input id="ciNote" value="${esc(c?.note||'')}" placeholder="Самочувствие, боль, что изменилось..."></div><div class="field"><label>Фото прогресса (необязательно)</label><input id="ciPhoto" type="file" accept="image/jpeg,image/png,image/webp"></div>${c?.photo_path?'<div class="muted small">Фото за сегодня уже сохранено. Новое заменит его в этом чек-ине.</div>':''}<button class="btn primary full" style="margin-top:14px" onclick="saveWeeklyCheckin()">Сохранить чек-ин</button>`)}
async function checkinUploadPhoto(file,date){if(!file||!cloud?.user)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=`${cloud.user.id}/${date}-${Date.now()}.${ext}`;const r=await cloud.client.storage.from('progress-photos').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type||'image/jpeg'});if(r.error)throw r.error;return path}
async function saveWeeklyCheckin(){if(!cloud?.user||!cloud?.client)return;const date=checkinToday(),weightRaw=$('#ciWeight')?.value,weight=weightRaw?Number(String(weightRaw).replace(',','.')):null,photo=$('#ciPhoto')?.files?.[0]||null,btn=$('#sheet .btn.primary');if(weight!=null&&(!Number.isFinite(weight)||weight<=0))return toast('Проверь вес');if(btn){btn.disabled=true;btn.textContent='Сохраняю…'}try{const old=await cloud.client.from('checkins').select('photo_path').eq('user_id',cloud.user.id).eq('checkin_date',date).maybeSingle();let photoPath=old.data?.photo_path||null;if(photo)photoPath=await checkinUploadPhoto(photo,date);const row={user_id:cloud.user.id,checkin_date:date,weight_kg:weight,sleep:+($('#ciSleep')?.value||3),energy:+($('#ciEnergy')?.value||3),stress:+($('#ciStress')?.value||3),soreness:+($('#ciSore')?.value||3),appetite:+($('#ciAppetite')?.value||3),note:$('#ciNote')?.value.trim()||'',photo_path:photoPath,updated_at:new Date().toISOString()};const r=await cloud.client.from('checkins').upsert(row,{onConflict:'user_id,checkin_date'}).select().single();if(r.error)throw r.error;if(weight){await cloud.client.from('bodyweights').upsert({user_id:cloud.user.id,measure_date:date,weight_kg:weight},{onConflict:'user_id,measure_date'});if(Array.isArray(st.bw)){const oldLocal=st.bw.find(x=>x.d===date);if(oldLocal)oldLocal.w=weight;else st.bw.push({d:date,w:weight});st.bw.sort((a,b)=>a.d.localeCompare(b.d));save()}}unvrslCheckinCache={at:Date.now(),data:r.data};closeModal();render();toast('Чек-ин сохранён')}catch(e){if(btn){btn.disabled=false;btn.textContent='Сохранить чек-ин'}alert('Не удалось сохранить чек-ин: '+(e.message||e))}}

function checkinDaysAgo(date){if(!date)return 999;return Math.floor((Date.now()-Date.parse(date+'T12:00:00'))/86400000)}
async function renderClientCheckinCard(){if(!cloud?.user)return;const root=$('#home');if(!root||root.querySelector('.weekly-checkin-card'))return;const c=await loadMyCheckin(),days=checkinDaysAgo(c?.checkin_date),due=days>=7,sig=checkinSignal(c),trainer=cloud?.profile?.role==='trainer'||(typeof trainerIsTrainer==='function'&&trainerIsTrainer());const card=document.createElement('div');card.className='card weekly-checkin-card';card.innerHTML=`<div class="row between"><div class="grow"><div class="muted small">${trainer?'МОЙ ЕЖЕНЕДЕЛЬНЫЙ ЧЕК-ИН':'ЕЖЕНЕДЕЛЬНЫЙ ЧЕК-ИН'}</div><div class="title" style="margin-top:4px">${due?'Пора отметить восстановление':`Готовность ${checkinScore(c)??'—'} / 100`}</div><div class="muted" style="margin-top:5px">${c?`Последний: ${esc(c.checkin_date)} · ${sig.label}`:'Вес, сон, стресс, крепатура и фото прогресса'}</div></div><button class="btn ${due?'primary':''}" onclick="openWeeklyCheckin()">${due?'Заполнить':'Открыть'}</button></div>`;root.insertBefore(card,root.firstChild)}
const _checkinHome=window.home;if(typeof _checkinHome==='function')window.home=function(){const r=_checkinHome.apply(this,arguments);setTimeout(renderClientCheckinCard,0);return r};

async function trainerCheckinOverview(){if(!cloud?.user||!(typeof trainerIsTrainer==='function'&&trainerIsTrainer()))return;const root=$('#clients');if(!root||root.querySelector('.checkin-overview'))return;const rel=await cloud.client.from('trainer_clients').select('client_id').eq('trainer_id',cloud.user.id).neq('status','archived');const ids=(rel.data||[]).map(x=>x.client_id);if(!ids.length)return;const cr=await cloud.client.from('checkins').select('user_id,checkin_date,sleep,energy,stress,soreness,appetite').in('user_id',ids).order('checkin_date',{ascending:false});const latest=new Map();(cr.data||[]).forEach(c=>{if(!latest.has(c.user_id))latest.set(c.user_id,c)});let attention=0,due=0;ids.forEach(id=>{const c=latest.get(id);if(!c||checkinDaysAgo(c.checkin_date)>=7)due++;if(c&&checkinScore(c)<68)attention++});const box=document.createElement('div');box.className='card checkin-overview';box.innerHTML=`<div class="row between"><div><div class="muted small">ЧЕК-ИНЫ КЛИЕНТОВ</div><div class="title" style="margin-top:4px">${attention?`${attention} требуют внимания`:'Восстановление под контролем'}</div></div><span class="chip ${attention?'orange':'green'}">${attention||'✓'}</span></div><div class="adv-stat-grid" style="margin-top:12px"><div class="adv-stat"><span>Пора заполнить</span><b>${due}</b></div><div class="adv-stat"><span>Низкое восстановление</span><b>${attention}</b></div></div>`;const metrics=$('#clientMetrics');if(metrics)metrics.insertAdjacentElement('afterend',box);else root.prepend(box)}
const _checkinClientsPage=window.clientsPage;if(typeof _checkinClientsPage==='function')window.clientsPage=async function(){const r=await _checkinClientsPage.apply(this,arguments);setTimeout(trainerCheckinOverview,0);return r};

async function checkinSignedPhoto(path){if(!path)return null;const r=await cloud.client.storage.from('progress-photos').createSignedUrl(path,3600);return r.error?null:r.data?.signedUrl||null}
const _checkinClientDetail=window.trainerClientDetail;if(typeof _checkinClientDetail==='function')window.trainerClientDetail=async function(id){const r=await _checkinClientDetail.apply(this,arguments);if(!cloud?.user)return r;const cr=await cloud.client.from('checkins').select('*').eq('user_id',id).order('checkin_date',{ascending:false}).limit(8);const a=cr.data||[],sh=$('#sheet');if(!sh)return r;const latest=a[0],sig=checkinSignal(latest),photo=latest?.photo_path?await checkinSignedPhoto(latest.photo_path):null;const root=document.createElement('div');root.className='client-checkin-detail';root.innerHTML=`<div class="section">ЧЕК-ИН</div>${latest?`<div class="card"><div class="row between"><div><b>${esc(latest.checkin_date)}</b><div class="muted small">Готовность ${checkinScore(latest)} / 100</div></div><span class="chip ${sig.cls}">${sig.label}</span></div><div class="adv-stat-grid" style="margin-top:12px"><div class="adv-stat"><span>Сон</span><b>${latest.sleep}/5</b></div><div class="adv-stat"><span>Энергия</span><b>${latest.energy}/5</b></div><div class="adv-stat"><span>Стресс</span><b>${latest.stress}/5</b></div><div class="adv-stat"><span>Крепатура</span><b>${latest.soreness}/5</b></div></div>${latest.weight_kg?`<div class="listline row between"><span>Вес</span><b>${latest.weight_kg} кг</b></div>`:''}${latest.note?`<div class="rule-card" style="margin-top:10px">${esc(latest.note)}</div>`:''}${photo?`<img src="${photo}" style="width:100%;border-radius:20px;margin-top:12px" loading="lazy">`:''}</div><div class="section">ИСТОРИЯ ЧЕК-ИНОВ</div>${a.map(c=>`<div class="history-row"><span>${esc(c.checkin_date)}</span><b>${checkinScore(c)}/100${c.weight_kg?` · ${c.weight_kg} кг`:''}</b></div>`).join('')}`:'<div class="card muted">Клиент ещё не заполнял чек-ин.</div>'}`;sh.appendChild(root);return r};

setTimeout(()=>{try{renderClientCheckinCard();trainerCheckinOverview()}catch(e){}},1200);
