'use strict';
(()=>{
  if(window.__unvrslOfflineClients)return;window.__unvrslOfflineClients=true;
  const FEMALE_STRENGTHS=[
    ['squat','Приседание со штангой'],
    ['hip_thrust','Ягодичный мост'],
    ['bulgarian_split_squat','Болгарские выпады'],
    ['lat_pulldown','Тяга верхнего блока'],
    ['seated_row','Тяга горизонтального блока'],
    ['bent_over_row','Тяга в наклоне'],
    ['lateral_raise','Махи гантелей в стороны'],
    ['upright_row','Протяжка на плечи'],
    ['rear_delt','Отведение на заднюю дельту']
  ];
  const MALE_STRENGTHS=[
    ['squat','Приседание со штангой'],['bench','Жим штанги лёжа'],['deadlift','Становая тяга'],['pullup','Подтягивания'],['row','Тяга в наклоне'],['ohp','Армейский жим']
  ];
  const s=document.createElement('style');s.textContent=`
    .client-tabs{display:grid;grid-template-columns:1fr 1fr;gap:5px;padding:5px;background:#1b1b1e;border:1px solid #323237;border-radius:18px;margin:12px 0 14px}.client-tabs button{border:0;background:transparent;color:#8e8e93;border-radius:14px;min-height:42px;font-weight:750;font-size:14px}.client-tabs button.on{background:#303034;color:#fff}.offline-client-card{display:block;width:100%;text-align:left}.offline-client-top{display:flex;align-items:center;justify-content:space-between;gap:10px}.offline-session-chip{white-space:nowrap}.offline-detail-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin:13px 0}.offline-detail-grid .metric{min-width:0}.offline-detail-grid .metric span{font-size:11px}.offline-detail-grid .metric b{font-size:18px}.offline-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:12px 0}.offline-actions .fullrow{grid-column:1/-1}.offline-strength-row{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:10px;padding:12px 0;border-bottom:1px solid #303034}.offline-strength-row:last-child{border-bottom:0}.offline-strength-row button{min-width:74px}.offline-delta{font-weight:800;color:var(--green)}.offline-delta.down{color:#ff9f0a}.offline-measure-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.offline-measure-grid .field{min-width:0}.offline-history{display:grid;grid-template-columns:84px 1fr auto;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #303034}.offline-history:last-child{border-bottom:0}.offline-session-stepper{display:flex;align-items:center;gap:8px}.offline-session-stepper .btn{min-width:44px}.offline-session-big{font-size:26px;font-weight:850;min-width:36px;text-align:center}.offline-note{white-space:pre-wrap}
    @media(max-width:390px){.offline-detail-grid{gap:6px}.offline-detail-grid .metric{padding:12px 8px}.offline-detail-grid .metric b{font-size:16px}.offline-actions{grid-template-columns:1fr}}
  `;document.head.appendChild(s);

  let activeTab='online';
  function ageFromBirth(v){if(!v)return null;const d=new Date(v+'T12:00:00');if(Number.isNaN(d.getTime()))return null;const n=new Date();let a=n.getFullYear()-d.getFullYear();const m=n.getMonth()-d.getMonth();if(m<0||(m===0&&n.getDate()<d.getDate()))a--;return a>=0&&a<130?a:null}
  function fmtNum(v,d=1){if(v==null||v==='')return'—';const n=Number(v);return Number.isFinite(n)?n.toFixed(d).replace('.0',''):'—'}
  function e1rm(w,r){w=Number(w)||0;r=Number(r)||0;if(!w||!r)return null;return +(r===1?w:w*(1+r/30)).toFixed(1)}
  function strengthPresets(sex){return sex==='male'?MALE_STRENGTHS:FEMALE_STRENGTHS}
  function measureValue(row,key){const n=Number(row?.measurements?.[key]);return Number.isFinite(n)&&n>0?n:null}
  function deltaText(now,prev,unit='см'){if(now==null||prev==null)return'';const d=+(now-prev).toFixed(1);if(!d)return'<span class="muted small">без изменений</span>';return `<span class="offline-delta ${d<0?'down':''}">${d>0?'+':''}${d} ${unit}</span>`}

  function switchTab(tab){activeTab=tab;const on=$('#onlineClientsPane'),off=$('#offlineClientsPane');if(on)on.style.display=tab==='online'?'':'none';if(off)off.style.display=tab==='offline'?'':'none';document.querySelectorAll('.client-tabs button').forEach(b=>b.classList.toggle('on',b.dataset.tab===tab));if(tab==='offline')renderOfflineClients()}
  window.offlineSwitchTab=switchTab;

  function installPanes(){
    const el=$('#clients');if(!el||!trainerIsTrainer?.())return;
    const metrics=$('#clientMetrics'),list=$('#clientList');if(!metrics||!list)return;
    if($('#onlineClientsPane')){switchTab(activeTab);return}
    const plans=[...el.children].find(x=>x.tagName==='BUTTON'&&/отправленные планы/i.test(x.textContent||''));
    const tabs=document.createElement('div');tabs.className='client-tabs';tabs.innerHTML='<button data-tab="online" onclick="offlineSwitchTab(\'online\')">Онлайн</button><button data-tab="offline" onclick="offlineSwitchTab(\'offline\')">Офлайн</button>';
    metrics.before(tabs);
    const online=document.createElement('div');online.id='onlineClientsPane';tabs.after(online);online.append(metrics,list);if(plans)online.append(plans);
    const offline=document.createElement('div');offline.id='offlineClientsPane';online.after(offline);
    const head=el.querySelector(':scope > .card .muted');if(head)head.textContent='Онлайн и офлайн клиенты · планы, занятия и прогресс';
    switchTab(activeTab);
  }

  async function renderOfflineClients(){
    const root=$('#offlineClientsPane');if(!root)return;if(!cloud?.ready||!cloud.user){root.innerHTML='<div class="card muted">Войди в тренерский аккаунт.</div>';return}
    root.innerHTML='<div class="card muted">Загружаю офлайн-клиентов…</div>';
    const cr=await cloud.client.from('offline_clients').select('*').eq('trainer_id',cloud.user.id).order('updated_at',{ascending:false});
    if(cr.error){root.innerHTML=`<div class="card muted">${esc(cr.error.message)}</div>`;return}
    const clients=cr.data||[],ids=clients.map(x=>x.id);let measures=[];
    if(ids.length){const mr=await cloud.client.from('offline_client_measurements').select('offline_client_id,measure_date,weight_kg,measurements').in('offline_client_id',ids).order('measure_date',{ascending:false});measures=mr.data||[]}
    const left=clients.reduce((a,x)=>a+(Number(x.sessions_remaining)||0),0);
    root.innerHTML=`<div class="metrics"><div class="metric"><span>Офлайн клиентов</span><b>${clients.length}</b></div><div class="metric"><span>Занятий осталось</span><b>${left}</b></div></div><button class="btn primary full" onclick="offlineNewClientSheet()">＋ Добавить офлайн-клиента</button><div class="section">ОФЛАЙН КЛИЕНТЫ</div><div id="offlineClientList">${clients.length?clients.map(c=>offlineClientCard(c,measures.find(m=>m.offline_client_id===c.id))).join(''):'<div class="card"><div class="title">Пока нет офлайн-клиентов</div><div class="muted" style="margin-top:6px">Добавь клиента, остаток занятий, замеры и силовые показатели.</div></div>'}</div>`;
  }
  window.renderOfflineClients=renderOfflineClients;

  function offlineClientCard(c,m){const a=ageFromBirth(c.birth_date),w=m?.weight_kg;return `<button class="card offline-client-card" onclick="offlineClientDetail('${c.id}')"><div class="offline-client-top"><div class="grow"><b>${esc(c.display_name)}</b><div class="catalog-meta">${c.height_cm?`${fmtNum(c.height_cm)} см · `:''}${w?`${fmtNum(w)} кг · `:''}${a!=null?`${a} лет`:(c.sex==='female'?'женщина':c.sex==='male'?'мужчина':'профиль')}</div></div><span class="chip offline-session-chip ${Number(c.sessions_remaining)<=2?'orange':'green'}">${c.sessions_remaining} зан.</span></div></button>`}

  window.offlineNewClientSheet=function(){modal(`<div class="sheet-grabber"></div><h2>Офлайн-клиент</h2><div class="field"><label>Имя</label><input id="offName" placeholder="Например, Анна"></div><div class="offline-measure-grid"><div class="field"><label>Пол</label><select id="offSex"><option value="female">Женский</option><option value="male">Мужской</option><option value="other">Другой</option></select></div><div class="field"><label>Осталось занятий</label><input id="offSessions" type="number" min="0" step="1" inputmode="numeric" value="8"></div><div class="field"><label>Рост, см</label><input id="offHeight" type="number" min="100" max="250" step="0.5" inputmode="decimal"></div><div class="field"><label>Дата рождения</label><input id="offBirth" type="date"></div></div><div class="field"><label>Заметка</label><textarea id="offNotes" placeholder="Цель, особенности, ограничения"></textarea></div><button class="btn primary full" onclick="offlineSaveNewClient()">Добавить клиента</button>`)};
  window.offlineSaveNewClient=async function(){const name=$('#offName')?.value.trim();if(!name)return toast('Введи имя');const payload={trainer_id:cloud.user.id,display_name:name,sex:$('#offSex')?.value||'female',sessions_remaining:Math.max(0,parseInt($('#offSessions')?.value||'0',10)||0),height_cm:Number($('#offHeight')?.value)||null,birth_date:$('#offBirth')?.value||null,notes:$('#offNotes')?.value.trim()||null,updated_at:new Date().toISOString()};const r=await cloud.client.from('offline_clients').insert(payload).select().single();if(r.error)return alert(r.error.message);closeModal();await renderOfflineClients();offlineClientDetail(r.data.id)};

  async function fetchDetail(id){const [c,m,sr]=await Promise.all([cloud.client.from('offline_clients').select('*').eq('id',id).single(),cloud.client.from('offline_client_measurements').select('*').eq('offline_client_id',id).order('measure_date',{ascending:false}).limit(20),cloud.client.from('offline_client_strengths').select('*').eq('offline_client_id',id).order('measured_at',{ascending:false}).order('created_at',{ascending:false})]);return{client:c.data,measurements:m.data||[],strengths:sr.data||[],error:c.error||m.error||sr.error}}
  window.offlineClientDetail=async function(id){const z=await fetchDetail(id);if(z.error||!z.client)return alert(z.error?.message||'Клиент не найден');const c=z.client,m=z.measurements,sr=z.strengths,latest=m[0],prev=m[1],age=ageFromBirth(c.birth_date),presets=strengthPresets(c.sex),custom=[...new Map(sr.map(x=>[x.exercise_key,[x.exercise_key,x.exercise_name]])).values()].filter(x=>!presets.some(p=>p[0]===x[0]));const ex=[...presets,...custom];modal(`<div class="sheet-grabber"></div><div class="row between"><div><div class="detail-title">${esc(c.display_name)}</div><div class="muted">Офлайн-клиент</div></div><button class="btn tiny" onclick="offlineEditClientSheet('${id}')">Изменить</button></div><div class="offline-detail-grid"><div class="metric"><span>Рост</span><b>${c.height_cm?`${fmtNum(c.height_cm)} см`:'—'}</b></div><div class="metric"><span>Вес</span><b>${latest?.weight_kg?`${fmtNum(latest.weight_kg)} кг`:'—'}</b></div><div class="metric"><span>Возраст</span><b>${age==null?'—':`${age} лет`}</b></div></div><div class="card"><div class="row between"><div><b>Осталось занятий</b><div class="muted small">Списывай после каждой очной тренировки</div></div><div class="offline-session-stepper"><button class="btn tiny" onclick="offlineAdjustSessions('${id}',-1)">−</button><span class="offline-session-big">${c.sessions_remaining}</span><button class="btn tiny" onclick="offlineAdjustSessions('${id}',1)">＋</button></div></div></div><div class="offline-actions"><button class="btn primary" onclick="offlineMeasurementSheet('${id}')">＋ Новый замер</button><button class="btn" onclick="offlineCustomStrengthSheet('${id}')">＋ Силовой показатель</button></div>${c.notes?`<div class="card"><b>Заметка</b><div class="muted offline-note" style="margin-top:7px">${esc(c.notes)}</div></div>`:''}<div class="section">ЗАМЕРЫ</div>${latest?offlineMeasurementsHtml(latest,prev,m):'<div class="card muted">Замеров пока нет.</div>'}<div class="section">СИЛОВЫЕ</div><div class="card">${ex.map(p=>offlineStrengthRow(id,p[0],p[1],sr.filter(x=>x.exercise_key===p[0]))).join('')}</div>`)};

  function offlineMeasurementsHtml(latest,prev,all){const keys=[['chest','Грудь'],['waist','Талия'],['abdomen','Живот'],['hips','Ягодицы'],['thigh','Бедро'],['arm','Рука'],['calf','Икра']];return `<div class="card"><div class="row between"><div><b>${esc(latest.measure_date)}</b><div class="muted small">Последний замер</div></div>${latest.weight_kg?`<div style="text-align:right"><b>${fmtNum(latest.weight_kg)} кг</b>${prev?.weight_kg?`<div>${deltaText(Number(latest.weight_kg),Number(prev.weight_kg),'кг')}</div>`:''}</div>`:''}</div><div class="offline-measure-grid" style="margin-top:12px">${keys.filter(k=>measureValue(latest,k[0])!=null).map(k=>`<div class="metric"><span>${k[1]}</span><b>${fmtNum(measureValue(latest,k[0]))} см</b>${prev?`<div>${deltaText(measureValue(latest,k[0]),measureValue(prev,k[0]))}</div>`:''}</div>`).join('')}</div>${all.length>1?`<button class="btn full" style="margin-top:10px" onclick="offlineMeasurementHistory('${latest.offline_client_id}')">История замеров · ${all.length}</button>`:''}</div>`}

  window.offlineAdjustSessions=async function(id,delta){const r=await cloud.client.from('offline_clients').select('sessions_remaining').eq('id',id).single();if(r.error)return alert(r.error.message);const next=Math.max(0,(Number(r.data.sessions_remaining)||0)+delta);const u=await cloud.client.from('offline_clients').update({sessions_remaining:next,updated_at:new Date().toISOString()}).eq('id',id);if(u.error)return alert(u.error.message);toast(delta<0?'Занятие списано':'Занятие добавлено');await renderOfflineClients();offlineClientDetail(id)};

  window.offlineEditClientSheet=async function(id){const r=await cloud.client.from('offline_clients').select('*').eq('id',id).single();if(r.error)return alert(r.error.message);const c=r.data;modal(`<div class="sheet-grabber"></div><h2>Редактировать клиента</h2><div class="field"><label>Имя</label><input id="offEditName" value="${esc(c.display_name)}"></div><div class="offline-measure-grid"><div class="field"><label>Пол</label><select id="offEditSex"><option value="female" ${c.sex==='female'?'selected':''}>Женский</option><option value="male" ${c.sex==='male'?'selected':''}>Мужской</option><option value="other" ${c.sex==='other'?'selected':''}>Другой</option></select></div><div class="field"><label>Рост, см</label><input id="offEditHeight" type="number" step="0.5" value="${c.height_cm??''}"></div><div class="field"><label>Дата рождения</label><input id="offEditBirth" type="date" value="${c.birth_date||''}"></div><div class="field"><label>Осталось занятий</label><input id="offEditSessions" type="number" min="0" value="${c.sessions_remaining}"></div></div><div class="field"><label>Заметка</label><textarea id="offEditNotes">${esc(c.notes||'')}</textarea></div><button class="btn primary full" onclick="offlineSaveClientEdit('${id}')">Сохранить</button>`)};
  window.offlineSaveClientEdit=async function(id){const name=$('#offEditName')?.value.trim();if(!name)return toast('Введи имя');const r=await cloud.client.from('offline_clients').update({display_name:name,sex:$('#offEditSex')?.value||'female',height_cm:Number($('#offEditHeight')?.value)||null,birth_date:$('#offEditBirth')?.value||null,sessions_remaining:Math.max(0,parseInt($('#offEditSessions')?.value||'0',10)||0),notes:$('#offEditNotes')?.value.trim()||null,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)return alert(r.error.message);closeModal();await renderOfflineClients();offlineClientDetail(id)};

  window.offlineMeasurementSheet=function(id){modal(`<div class="sheet-grabber"></div><h2>Новый замер</h2><div class="field"><label>Дата</label><input id="omDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="offline-measure-grid"><div class="field"><label>Вес, кг</label><input id="omWeight" type="number" step="0.1" inputmode="decimal"></div><div class="field"><label>Грудь, см</label><input id="omChest" type="number" step="0.1"></div><div class="field"><label>Талия, см</label><input id="omWaist" type="number" step="0.1"></div><div class="field"><label>Живот, см</label><input id="omAbdomen" type="number" step="0.1"></div><div class="field"><label>Ягодицы, см</label><input id="omHips" type="number" step="0.1"></div><div class="field"><label>Бедро, см</label><input id="omThigh" type="number" step="0.1"></div><div class="field"><label>Рука, см</label><input id="omArm" type="number" step="0.1"></div><div class="field"><label>Икра, см</label><input id="omCalf" type="number" step="0.1"></div></div><div class="field"><label>Комментарий</label><input id="omNotes" placeholder="Например, замер утром"></div><button class="btn primary full" onclick="offlineSaveMeasurement('${id}')">Сохранить замер</button>`)};
  window.offlineSaveMeasurement=async function(id){const val=k=>{const n=Number($(k)?.value);return n>0?n:null},measurements={chest:val('#omChest'),waist:val('#omWaist'),abdomen:val('#omAbdomen'),hips:val('#omHips'),thigh:val('#omThigh'),arm:val('#omArm'),calf:val('#omCalf')};Object.keys(measurements).forEach(k=>measurements[k]==null&&delete measurements[k]);const r=await cloud.client.from('offline_client_measurements').insert({offline_client_id:id,trainer_id:cloud.user.id,measure_date:$('#omDate')?.value||new Date().toISOString().slice(0,10),weight_kg:val('#omWeight'),measurements,notes:$('#omNotes')?.value.trim()||null});if(r.error)return alert(r.error.message);await cloud.client.from('offline_clients').update({updated_at:new Date().toISOString()}).eq('id',id);toast('Замер сохранён');offlineClientDetail(id)};
  window.offlineMeasurementHistory=async function(id){const r=await cloud.client.from('offline_client_measurements').select('*').eq('offline_client_id',id).order('measure_date',{ascending:false}).limit(30);if(r.error)return alert(r.error.message);modal(`<div class="sheet-grabber"></div><h2>История замеров</h2>${(r.data||[]).map(x=>`<div class="offline-history"><span class="muted small">${esc(x.measure_date)}</span><span>${x.weight_kg?`<b>${fmtNum(x.weight_kg)} кг</b>`:'<span class="muted">без веса</span>'}<div class="muted small">${[['waist','талия'],['hips','ягодицы'],['thigh','бедро']].filter(k=>measureValue(x,k[0])!=null).map(k=>`${k[1]} ${fmtNum(measureValue(x,k[0]))}`).join(' · ')}</div></span><span class="muted">›</span></div>`).join('')||'<div class="muted">Нет данных.</div>'}`)};

  function offlineStrengthRow(id,key,name,rows){const latest=rows[0],chron=[...rows].reverse(),first=chron[0],best=rows.reduce((a,x)=>Math.max(a,Number(x.e1rm)||Number(x.weight_kg)||0),0),now=latest?(Number(latest.e1rm)||Number(latest.weight_kg)||0):0,growth=first&&now?((now-(Number(first.e1rm)||Number(first.weight_kg)||0))/(Number(first.e1rm)||Number(first.weight_kg)||1)*100):0;return `<div class="offline-strength-row"><div><b>${esc(name)}</b><div class="muted small">${latest?`${fmtNum(latest.weight_kg)} кг × ${latest.reps||'—'}${latest.e1rm?` · 1ПМ ≈ ${fmtNum(latest.e1rm)} кг`:''}`:'Нет данных'}${rows.length>1?` · лучший ≈ ${fmtNum(best)} кг`:''}</div>${rows.length>1?`<div class="offline-delta ${growth<0?'down':''}">${growth>=0?'+':''}${growth.toFixed(1)}%</div>`:''}</div><button class="btn tiny" onclick="offlineStrengthSheet('${id}','${encodeURIComponent(key)}','${encodeURIComponent(name)}')">${latest?'＋':'Записать'}</button></div>`}
  window.offlineStrengthSheet=function(id,keyToken,nameToken){const key=decodeURIComponent(keyToken),name=decodeURIComponent(nameToken);modal(`<div class="sheet-grabber"></div><h2>${esc(name)}</h2><div class="muted">Запиши лучший рабочий подход или контрольный сет</div><div class="field"><label>Дата</label><input id="osDate" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="offline-measure-grid"><div class="field"><label>Вес / нагрузка, кг</label><input id="osWeight" type="number" min="0" step="0.5" inputmode="decimal"></div><div class="field"><label>Повторения</label><input id="osReps" type="number" min="1" max="100" step="1" inputmode="numeric"></div></div><div class="field"><label>Комментарий</label><input id="osNotes" placeholder="Тренажёр, техника, вес гантелей и т. п."></div><button class="btn primary full" onclick="offlineSaveStrength('${id}','${encodeURIComponent(key)}','${encodeURIComponent(name)}')">Сохранить</button><button class="btn full" onclick="offlineStrengthHistory('${id}','${encodeURIComponent(key)}','${encodeURIComponent(name)}')">История показателя</button>`)};
  window.offlineCustomStrengthSheet=function(id){modal(`<div class="sheet-grabber"></div><h2>Другой силовой показатель</h2><div class="field"><label>Упражнение</label><input id="osCustomName" placeholder="Название упражнения"></div><button class="btn primary full" onclick="offlineOpenCustomStrength('${id}')">Далее</button>`)};
  window.offlineOpenCustomStrength=function(id){const name=$('#osCustomName')?.value.trim();if(!name)return toast('Введи упражнение');const key='custom_'+name.toLowerCase().replace(/[^a-zа-я0-9]+/gi,'_').replace(/^_|_$/g,'');offlineStrengthSheet(id,encodeURIComponent(key),encodeURIComponent(name))};
  window.offlineSaveStrength=async function(id,keyToken,nameToken){const key=decodeURIComponent(keyToken),name=decodeURIComponent(nameToken),w=Number($('#osWeight')?.value)||null,reps=parseInt($('#osReps')?.value||'0',10)||null;if(!w&&!reps)return toast('Введи вес и повторения');const r=await cloud.client.from('offline_client_strengths').insert({offline_client_id:id,trainer_id:cloud.user.id,measured_at:$('#osDate')?.value||new Date().toISOString().slice(0,10),exercise_key:key,exercise_name:name,weight_kg:w,reps,e1rm:w&&reps?e1rm(w,reps):null,notes:$('#osNotes')?.value.trim()||null});if(r.error)return alert(r.error.message);await cloud.client.from('offline_clients').update({updated_at:new Date().toISOString()}).eq('id',id);toast('Показатель сохранён');offlineClientDetail(id)};
  window.offlineStrengthHistory=async function(id,keyToken,nameToken){const key=decodeURIComponent(keyToken),name=decodeURIComponent(nameToken);const r=await cloud.client.from('offline_client_strengths').select('*').eq('offline_client_id',id).eq('exercise_key',key).order('measured_at',{ascending:false}).order('created_at',{ascending:false});if(r.error)return alert(r.error.message);modal(`<div class="sheet-grabber"></div><h2>${esc(name)}</h2><div class="muted">Динамика силового показателя</div>${(r.data||[]).map(x=>`<div class="offline-history"><span class="muted small">${esc(x.measured_at)}</span><span><b>${fmtNum(x.weight_kg)} кг × ${x.reps||'—'}</b>${x.notes?`<div class="muted small">${esc(x.notes)}</div>`:''}</span><b>${x.e1rm?`≈${fmtNum(x.e1rm)}`:''}</b></div>`).join('')||'<div class="card muted">Истории пока нет.</div>'}`)};

  function install(){const base=window.clientsPage;if(typeof base!=='function'||base.__offlineWrapped)return;const wrapped=async function(){const r=await base.apply(this,arguments);installPanes();return r};wrapped.__offlineWrapped=true;window.clientsPage=wrapped;try{clientsPage=wrapped}catch(e){};if($('#clients')?.classList.contains('active'))wrapped()}
  install();setTimeout(install,250);setTimeout(install,1200);
})();
