'use strict';
const OG_LIBRARY_URL='https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/data/exercises.json';
const OG_MEDIA_BASE='https://raw.githubusercontent.com/hasaneyldrm/exercises-dataset/main/';
const OG_SOURCE_URL='https://github.com/hasaneyldrm/exercises-dataset';
const BP_RU={'upper legs':'Бёдра','lower legs':'Голени','chest':'Грудь','back':'Спина','shoulders':'Плечи','upper arms':'Руки','lower arms':'Предплечья','waist':'Кор','cardio':'Кардио','neck':'Шея'};
const EQ_RU={'barbell':'Штанга','dumbbell':'Гантели','cable':'Блок','body weight':'Свой вес','leverage machine':'Тренажёр','assisted':'С поддержкой','band':'Резина','smith machine':'Смит','kettlebell':'Гиря','ez barbell':'EZ-штанга','medicine ball':'Медбол','stability ball':'Фитбол','roller':'Ролик','rope':'Канат','sled machine':'Жим-платформа','weighted':'Отягощение','bosu ball':'BOSU','olympic barbell':'Олимпийская штанга'};
const TARGET_RU={'abs':'Пресс','pectorals':'Грудные','pectoralis major':'Грудные','lats':'Широчайшие','upper back':'Верх спины','spine':'Разгибатели спины','glutes':'Ягодичные','quads':'Квадрицепсы','hamstrings':'Бицепс бедра','calves':'Икроножные','triceps':'Трицепс','biceps':'Бицепс','delts':'Дельты','forearms':'Предплечья','traps':'Трапеции','adductors':'Приводящие','abductors':'Отводящие','hip flexors':'Сгибатели бедра','cardiovascular system':'Кардио','serratus anterior':'Передняя зубчатая'};
const EXACT_RU={
 'barbell bench press':'Жим штанги лёжа','barbell high bar squat':'Присед со штангой high-bar','barbell full squat':'Глубокий присед со штангой','barbell front squat':'Фронтальный присед со штангой','barbell deadlift':'Становая тяга со штангой','barbell romanian deadlift':'Румынская тяга со штангой','barbell bent over row':'Тяга штанги в наклоне','barbell standing military press':'Армейский жим стоя','barbell curl':'Сгибание рук со штангой','barbell incline bench press':'Жим штанги на наклонной скамье','barbell close-grip bench press':'Жим штанги узким хватом','barbell glute bridge':'Ягодичный мост со штангой','dumbbell bench press':'Жим гантелей лёжа','dumbbell incline bench press':'Жим гантелей на наклонной скамье','dumbbell lateral raise':'Махи гантелей в стороны','dumbbell front raise':'Подъём гантелей перед собой','dumbbell shoulder press':'Жим гантелей над головой','dumbbell biceps curl':'Сгибание рук с гантелями','dumbbell hammer curl':'Молотковые сгибания с гантелями','dumbbell fly':'Разведение гантелей лёжа','assisted pull-up':'Подтягивания в гравитроне','pull-up':'Подтягивания','chin-up':'Подтягивания обратным хватом','push-up':'Отжимания','air bike':'Велосипедные скручивания','russian twist':'Русские повороты','plank':'Планка','lever leg extension':'Разгибание ног в тренажёре','lever lying leg curl':'Сгибание ног лёжа в тренажёре','lever seated leg curl':'Сгибание ног сидя в тренажёре','lever seated leg press':'Жим ногами в тренажёре','cable lat pulldown':'Тяга верхнего блока','cable seated row':'Тяга нижнего блока сидя','cable rope pushdown':'Разгибание рук с канатом','cable pushdown':'Разгибание рук на блоке','cable crossover':'Кроссовер на грудь','pec deck fly':'Бабочка на грудь','lever pec deck fly':'Бабочка на грудь','standing calf raise':'Подъём на носки стоя','seated calf raise':'Подъём на носки сидя','hip thrust':'Ягодичный мост','barbell hip thrust':'Ягодичный мост со штангой'
};
const RU_REPL=[
 ['romanian deadlift','румынская тяга'],['stiff leg deadlift','тяга на прямых ногах'],['deadlift','становая тяга'],['incline bench press','жим на наклонной скамье'],['decline bench press','жим на отрицательной скамье'],['bench press','жим лёжа'],['close-grip','узким хватом'],['wide-grip','широким хватом'],['reverse-grip','обратным хватом'],['underhand','обратным хватом'],['overhand','прямым хватом'],['bent over row','тяга в наклоне'],['seated row','тяга сидя'],['lat pulldown','тяга верхнего блока'],['pulldown','тяга верхнего блока'],['pull-up','подтягивания'],['chin-up','подтягивания обратным хватом'],['push-up','отжимания'],['split squat','сплит-присед'],['squat','приседания'],['leg press','жим ногами'],['leg extension','разгибание ног'],['leg curl','сгибание ног'],['calf raise','подъём на носки'],['hip thrust','ягодичный мост'],['glute bridge','ягодичный мост'],['lateral raise','махи в стороны'],['front raise','подъём перед собой'],['rear delt fly','разведение на заднюю дельту'],['reverse fly','обратное разведение'],['shoulder press','жим над головой'],['overhead press','жим над головой'],['military press','армейский жим'],['biceps curl','сгибание на бицепс'],['hammer curl','молотковые сгибания'],['triceps extension','разгибание на трицепс'],['triceps dip','отжимания на брусьях на трицепс'],['chest dip','отжимания на брусьях на грудь'],['wrist curl','сгибание кистей'],['shrug','шраги'],['fly','разведение'],['crunch','скручивания'],['sit-up','подъём корпуса'],['russian twist','русские повороты'],['step-up','зашагивания'],['lunge','выпад'],['good morning','наклоны good morning'],['face pull','тяга к лицу'],['plank','планка'],['standing','стоя'],['seated','сидя'],['lying','лёжа'],['kneeling','на коленях'],['one arm','одной рукой'],['single arm','одной рукой'],['single leg','на одной ноге'],['alternate','попеременно'],['alternating','попеременно'],['assisted','с поддержкой'],['barbell','со штангой'],['dumbbell','с гантелями'],['kettlebell','с гирей'],['cable','на блоке'],['band','с резиной'],['smith machine','в Смите'],['smith','в Смите'],['lever','в тренажёре'],['weighted','с отягощением'],['body weight','с собственным весом']
];
let ogLibrary=[],ogLibraryLoaded=false,ogLibraryLoading=false,ogLibraryError='';
let exQuery='',exBody='all';
let rmState={id:null,w:20,r:5};
function ruTarget(x=''){return TARGET_RU[String(x).toLowerCase()]||x||'—'}
function ruExerciseName(name=''){
 const raw=String(name||'').trim();if(!raw)return'Упражнение';if(/[А-Яа-яЁё]/.test(raw))return raw;
 let s=raw.toLowerCase().replace(/\((male|female)\)/g,'').replace(/\s+/g,' ').trim();if(EXACT_RU[s])return EXACT_RU[s];
 for(const [a,b] of RU_REPL)s=s.split(a).join(b);
 s=s.replace(/\s+/g,' ').replace(/\s+([,.)])/g,'$1').trim();return s.charAt(0).toUpperCase()+s.slice(1)
}
function mediaUrl(path=''){if(!path)return'';return /^https?:/i.test(path)?path:OG_MEDIA_BASE+String(path).replace(/^\.?\//,'')}
function normalizeExercise(x){return{id:String(x.id),n:x.name||x.n||'Exercise',bp:x.body_part||x.category||x.bp||'',tg:x.target||x.tg||'',eq:x.equipment||x.eq||'',secondary:x.secondary_muscles||[],instructions:x.instructions||{},image:x.image||'',gif:x.gif_url||x.gif||'',attribution:x.attribution||'',mediaId:x.media_id||'',custom:false}}
function exercisesPage(){
 $('#exercises').innerHTML=`<div class="card catalog-head"><div class="row between"><div><div class="title">Упражнения</div><div class="muted" id="catalogCount">${ogLibraryLoaded?`Русская база · ${ogLibrary.length} упражнений`:'Загружаю базу упражнений…'}</div></div><span class="chip green">RU + GIF</span></div></div><input id="exSearch" class="search" placeholder="Поиск по-русски или по-английски" value="${esc(exQuery)}" oninput="setExerciseQuery(this.value)"><div id="bodyFilters" class="filterbar"></div><div id="exList"></div>`;
 renderBodyFilters();renderExerciseResults();if(!ogLibraryLoaded&&!ogLibraryLoading)loadExerciseDB();
}
async function loadExerciseDB(force=false){
 if(ogLibraryLoading)return;if(ogLibraryLoaded&&!force)return;ogLibraryLoading=true;ogLibraryError='';
 try{const res=await fetch(OG_LIBRARY_URL,{cache:force?'reload':'default'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const d=await res.json();const arr=Array.isArray(d)?d:d.exercises;if(!Array.isArray(arr)||arr.length<1000)throw new Error('Неполная база');ogLibrary=arr.map(normalizeExercise);ogLibraryLoaded=true}
 catch(e){ogLibraryError=String(e.message||e)}finally{ogLibraryLoading=false;refreshCatalogUI()}
}
function refreshCatalogUI(){const c=$('#catalogCount');if(c)c.textContent=ogLibraryLoaded?`Русская база · ${ogLibrary.length} упражнений`:ogLibraryError?`Не удалось загрузить базу: ${ogLibraryError}`:'Загружаю базу упражнений…';renderBodyFilters();renderExerciseResults()}
function setExerciseQuery(q){exQuery=q||'';renderExerciseResults()}
function setExerciseBody(bp){exBody=bp;renderBodyFilters();renderExerciseResults()}
function renderBodyFilters(){const el=$('#bodyFilters');if(!el)return;const parts=['all','upper legs','chest','back','shoulders','upper arms','lower legs','waist','cardio'];el.innerHTML=parts.map(bp=>`<button class="filterchip ${exBody===bp?'on':''}" onclick="setExerciseBody('${bp}')">${bp==='all'?'Все':BP_RU[bp]||bp}</button>`).join('')}
function inferCustomMeta(n){const x=baseExerciseName(n).toLowerCase();let bp='upper arms',tg='',eq='custom';if(/присед|жим ногами|разгибание ног|выпад|зашаг|сведение ног|разведение ног/.test(x)){bp='upper legs';tg=/свед/.test(x)?'adductors':/развед/.test(x)?'glutes':'quads';eq=/присед/.test(x)?'barbell':'leverage machine'}else if(/румын|ягодич|сгибание ног/.test(x)){bp='upper legs';tg=/сгибание/.test(x)?'hamstrings':'glutes';eq=/румын/.test(x)?'barbell':'leverage machine'}else if(/икр/.test(x)){bp='lower legs';tg='calves';eq='leverage machine'}else if(/жим лёжа|наклонн|кроссовер|разводк|бабочк|отжиман/.test(x)){bp='chest';tg='pectorals';eq=/гантел/.test(x)?'dumbbell':/кроссовер/.test(x)?'cable':/жим лёжа/.test(x)?'barbell':'leverage machine'}else if(/тяга|подтяг|верхний блок|нижний блок|гиперэкст/.test(x)){bp='back';tg=/подтяг|верхний/.test(x)?'lats':'upper back';eq=/штанг/.test(x)?'barbell':/т-гриф/.test(x)?'leverage machine':/подтяг/.test(x)?'body weight':'cable'}else if(/плеч|дельт|мах[и]|армей/.test(x)){bp='shoulders';tg='delts';eq=/гантел|мах/.test(x)?'dumbbell':/армей/.test(x)?'barbell':'leverage machine'}else if(/бицеп|сгибан|скотт|молот/.test(x)){bp='upper arms';tg='biceps';eq=/гантел/.test(x)?'dumbbell':/канат|блок/.test(x)?'cable':'barbell'}else if(/трицеп|француз|разгибание гантели/.test(x)){bp='upper arms';tg='triceps';eq=/гантел/.test(x)?'dumbbell':/канат|блок/.test(x)?'cable':'ez barbell'}else if(/аэробайк/.test(x)){bp='cardio';tg='cardiovascular system';eq='cardio'}return{bp,tg,eq}}
function customCatalog(){const names=[];ROUTINES.forEach(r=>routineEntries(r).forEach(e=>{const b=baseExerciseName(e.n);if(b&&!names.includes(b))names.push(b)}));(st.customExercises||[]).forEach(e=>{if(e.n&&!names.includes(e.n))names.push(e.n)});return names.map(n=>({id:`custom:${n}`,n:displayExerciseName(n),raw:n,...inferCustomMeta(n),custom:true}))}
function catalogRecords(){const custom=customCatalog(),builtin=ogLibrary.map(e=>({...e,id:`og:${e.id}`,rawId:e.id,custom:false}));return[...custom,...builtin]}
function renderExerciseResults(){const el=$('#exList');if(!el)return;const q=exQuery.trim().toLowerCase(),all=catalogRecords();let filtered=all.filter(e=>{const hay=`${e.n} ${ruExerciseName(e.n)} ${e.tg||''} ${ruTarget(e.tg)} ${e.eq||''} ${EQ_RU[e.eq]||''} ${BP_RU[e.bp]||''}`.toLowerCase();return(exBody==='all'||e.bp===exBody)&&(!q||hay.includes(q))});const total=filtered.length;filtered=filtered.slice(0,140);el.innerHTML=`${filtered.map(exerciseLibRow).join('')}${total>140?`<div class="card muted" style="text-align:center">Показаны первые 140 из ${total}. Уточни поиск.</div>`:''}${!filtered.length?`<div class="card muted">${ogLibraryLoading?'Загружаю базу…':'Ничего не найдено.'}</div>`:''}`}
function exerciseLibRow(ex){const body=BP_RU[ex.bp]||ex.bp||'—',eq=ex.custom?'Своё':(EQ_RU[ex.eq]||ex.eq||'—'),target=ruTarget(ex.tg),rec=recordsFor(ex.raw||ex.n),title=ex.custom?ex.n:ruExerciseName(ex.n),img=!ex.custom&&ex.image?mediaUrl(ex.image):'';return `<button class="card exlib exlib-btn" onclick="openExerciseDetail('${encodeURIComponent(ex.id)}')"><div class="exercise-list-row">${img?`<img class="ex-thumb" loading="lazy" src="${img}" alt="${esc(title)}">`:`<div class="ex-thumb placeholder">🏋︎</div>`}<div class="grow"><b>${esc(title)}</b>${!ex.custom&&title.toLowerCase()!==String(ex.n).toLowerCase()?`<div class="english-name">${esc(ex.n)}</div>`:''}<div class="catalog-meta">${esc(body)} · ${esc(eq)} · ${esc(target)}</div></div>${rec.best?`<span class="chip green">${rec.best} кг</span>`:'<span class="chev">›</span>'}</div></button>`}
function recordsFor(n){const target=baseExerciseName(n).toLowerCase();let count=0,best=0;st.sessions.forEach(s=>s.ex.filter(e=>baseExerciseName(e.n).toLowerCase()===target).forEach(e=>e.set.filter(x=>x.ok).forEach(x=>{count++;best=Math.max(best,+x.w||0)})));return{count,best}}
function findExercise(token){const id=decodeURIComponent(token||'');if(id.startsWith('custom:')){const raw=id.slice(7),meta=inferCustomMeta(raw),media=findMediaForCustom(raw);return{id,n:displayExerciseName(raw),raw,...meta,...(media||{}),sourceName:media?.n||'',custom:true}}if(id.startsWith('og:')){const rawId=id.slice(3),x=ogLibrary.find(e=>e.id===rawId);return x?{...x,id,rawId,custom:false}:null}return null}
function findMediaForCustom(raw=''){if(!ogLibraryLoaded)return null;const q=String(raw).toLowerCase();const tests=[];if(/присед.*hb|high.?bar/.test(q))tests.push('barbell high bar squat');if(/жим лёжа/.test(q))tests.push('barbell bench press');if(/тяга штанги.*наклон/.test(q))tests.push('barbell bent over row');if(/румын/.test(q))tests.push('barbell romanian deadlift');if(/жим ногами/.test(q))tests.push('leg press');if(/разгибание ног/.test(q))tests.push('leg extension');if(/сгибание ног.*л[её]жа/.test(q))tests.push('lying leg curl');if(/наклонн.*гантел|гантел.*наклон/.test(q))tests.push('dumbbell incline bench press');if(/махи.*гантел|развед.*дельт/.test(q))tests.push('dumbbell lateral raise');if(/т-гриф|t.?bar/.test(q))tests.push('t-bar row');if(/армей/.test(q))tests.push('military press');if(/подтяг/.test(q))tests.push('pull-up');if(/ягодич.*мост/.test(q))tests.push('barbell glute bridge');if(/верхн.*блок/.test(q))tests.push('lat pulldown');for(const t of tests){const x=ogLibrary.find(e=>String(e.n).toLowerCase().includes(t));if(x)return x}return null}
function openExerciseDetail(token){const ex=findExercise(token);if(!ex)return toast('Упражнение не найдено');const best=bestEstimateFor(ex.raw||ex.n);rmState={id:ex.id,w:best?.w||20,r:best?.r||5};renderExerciseDetail(ex)}
function openExerciseDetailByName(token){const raw=decodeURIComponent(token||''),media=findMediaForCustom(raw);const ex={id:`custom:${raw}`,n:displayExerciseName(raw),raw,...inferCustomMeta(raw),...(media||{}),sourceName:media?.n||'',custom:true};const best=bestEstimateFor(raw);rmState={id:ex.id,w:best?.w||20,r:best?.r||5};renderExerciseDetail(ex)}
