'use strict';
const OG_LIBRARY_URL='https://raw.githubusercontent.com/alexpcosta/opengym/main/api/coach/library.json';
const OG_SOURCE_URL='https://github.com/DuarteSantos8/openGym';
const OG_CACHE_KEY='unvrsl-fit-opengym-library-v1';
const BP_RU={'upper legs':'Бёдра','lower legs':'Голени','chest':'Грудь','back':'Спина','shoulders':'Плечи','upper arms':'Руки','lower arms':'Предплечья','waist':'Кор','cardio':'Кардио','neck':'Шея'};
const EQ_RU={'barbell':'Штанга','dumbbell':'Гантели','cable':'Блок','body weight':'Свой вес','leverage machine':'Тренажёр','assisted':'С поддержкой','band':'Резина','smith machine':'Смит','kettlebell':'Гиря','ez barbell':'EZ-штанга','medicine ball':'Медбол','stability ball':'Фитбол','roller':'Ролик','rope':'Канат','sled machine':'Тренажёр','weighted':'Отягощение'};
let ogLibrary=[],ogLibraryLoaded=false,ogLibraryLoading=false,ogLibraryError='';
let exQuery='',exBody='all';
let rmState={id:null,w:20,r:5};
function exercisesPage(){
  $('#exercises').innerHTML=`<div class="card catalog-head"><div class="row between"><div><div class="title">Упражнения</div><div class="muted" id="catalogCount">${ogLibraryLoaded?`База openGym · ${ogLibrary.length} упражнений`:'Загружаю базу openGym…'}</div></div><span class="chip green">openGym</span></div></div><input id="exSearch" class="search" placeholder="Поиск по 1324 упражнениям" value="${esc(exQuery)}" oninput="setExerciseQuery(this.value)"><div id="bodyFilters" class="filterbar"></div><div id="exList"></div>`;
  renderBodyFilters();renderExerciseResults();if(!ogLibraryLoaded&&!ogLibraryLoading)loadExerciseDB();
}
async function loadExerciseDB(force=false){
  if(ogLibraryLoading)return;if(ogLibraryLoaded&&!force)return;ogLibraryLoading=true;ogLibraryError='';
  try{
    if(!force){try{const c=JSON.parse(localStorage.getItem(OG_CACHE_KEY)||'null');if(c?.exercises?.length>1000){ogLibrary=c.exercises;ogLibraryLoaded=true;ogLibraryLoading=false;refreshCatalogUI();return}}catch(e){}}
    const res=await fetch(OG_LIBRARY_URL,{cache:'no-cache'});if(!res.ok)throw new Error(`HTTP ${res.status}`);const d=await res.json();if(!Array.isArray(d.exercises)||d.exercises.length<1000)throw new Error('Неполная база');ogLibrary=d.exercises;ogLibraryLoaded=true;try{localStorage.setItem(OG_CACHE_KEY,JSON.stringify({count:d.count||d.exercises.length,exercises:d.exercises,at:Date.now()}))}catch(e){}
  }catch(e){ogLibraryError=String(e.message||e)}finally{ogLibraryLoading=false;refreshCatalogUI()}
}
function refreshCatalogUI(){const c=$('#catalogCount');if(c)c.textContent=ogLibraryLoaded?`База openGym · ${ogLibrary.length} упражнений`:ogLibraryError?`Не удалось загрузить базу: ${ogLibraryError}`:'Загружаю базу openGym…';renderBodyFilters();renderExerciseResults()}
function setExerciseQuery(q){exQuery=q||'';renderExerciseResults()}
function setExerciseBody(bp){exBody=bp;renderBodyFilters();renderExerciseResults()}
function renderBodyFilters(){const el=$('#bodyFilters');if(!el)return;const parts=['all','upper legs','chest','back','shoulders','upper arms','lower legs','waist','cardio'];el.innerHTML=parts.map(bp=>`<button class="filterchip ${exBody===bp?'on':''}" onclick="setExerciseBody('${bp}')">${bp==='all'?'Все':BP_RU[bp]||bp}</button>`).join('')}
function inferCustomMeta(n){const x=baseExerciseName(n).toLowerCase();let bp='upper arms',tg='',eq='custom';if(/присед|жим ногами|разгибание ног|выпад|зашаг|сведение ног|разведение ног/.test(x)){bp='upper legs';tg=/свед/.test(x)?'adductors':/развед/.test(x)?'glutes':'quads';eq=/присед/.test(x)?'barbell':'leverage machine'}else if(/румын|ягодич|сгибание ног/.test(x)){bp='upper legs';tg=/сгибание/.test(x)?'hamstrings':'glutes';eq=/румын/.test(x)?'barbell':'leverage machine'}else if(/икр/.test(x)){bp='lower legs';tg='calves';eq='leverage machine'}else if(/жим лёжа|наклонн|кроссовер|разводк|бабочк|отжиман/.test(x)){bp='chest';tg='pectorals';eq=/гантел/.test(x)?'dumbbell':/кроссовер/.test(x)?'cable':/жим лёжа/.test(x)?'barbell':'leverage machine'}else if(/тяга|подтяг|верхний блок|нижний блок|гиперэкст/.test(x)){bp='back';tg=/подтяг|верхний/.test(x)?'lats':'upper back';eq=/штанг/.test(x)?'barbell':/т-гриф/.test(x)?'leverage machine':/подтяг/.test(x)?'body weight':'cable'}else if(/плеч|дельт|мах[и]|армей/.test(x)){bp='shoulders';tg='delts';eq=/гантел|мах/.test(x)?'dumbbell':/армей/.test(x)?'barbell':'leverage machine'}else if(/бицеп|сгибан|скотт|молот/.test(x)){bp='upper arms';tg='biceps';eq=/гантел/.test(x)?'dumbbell':/канат|блок/.test(x)?'cable':'barbell'}else if(/трицеп|француз|разгибание гантели/.test(x)){bp='upper arms';tg='triceps';eq=/гантел/.test(x)?'dumbbell':/канат|блок/.test(x)?'cable':'ez barbell'}else if(/аэробайк/.test(x)){bp='cardio';tg='cardiovascular system';eq='cardio'}return{bp,tg,eq}}
function customCatalog(){const names=[];ROUTINES.forEach(r=>routineEntries(r).forEach(e=>{const b=baseExerciseName(e.n);if(b&&!names.includes(b))names.push(b)}));(st.customExercises||[]).forEach(e=>{if(e.n&&!names.includes(e.n))names.push(e.n)});return names.map(n=>({id:`custom:${n}`,n:displayExerciseName(n),raw:n,...inferCustomMeta(n),custom:true}))}
function catalogRecords(){const custom=customCatalog(),builtin=ogLibrary.map(e=>({...e,id:`og:${e.id}`,rawId:e.id,custom:false}));return [...custom,...builtin]}
function renderExerciseResults(){const el=$('#exList');if(!el)return;const q=exQuery.trim().toLowerCase(),all=catalogRecords();let filtered=all.filter(e=>(exBody==='all'||e.bp===exBody)&&(!q||`${e.n} ${e.tg||''} ${e.eq||''} ${BP_RU[e.bp]||''}`.toLowerCase().includes(q)));const total=filtered.length;filtered=filtered.slice(0,140);el.innerHTML=`${filtered.map(exerciseLibRow).join('')}${total>140?`<div class="card muted" style="text-align:center">Показаны первые 140 из ${total}. Уточни поиск.</div>`:''}${!filtered.length?`<div class="card muted">${ogLibraryLoading?'Загружаю базу…':'Ничего не найдено.'}</div>`:''}`}
function exerciseLibRow(ex){const body=BP_RU[ex.bp]||ex.bp||'—',eq=ex.custom?'Своё':(EQ_RU[ex.eq]||ex.eq||'openGym'),rec=recordsFor(ex.raw||ex.n);return `<button class="card exlib exlib-btn" onclick="openExerciseDetail('${encodeURIComponent(ex.id)}')"><div class="row between"><div class="grow"><b>${esc(ex.n)}</b><div class="catalog-meta">${esc(body)} · ${esc(eq)}${ex.tg?` · ${esc(ex.tg)}`:''}</div></div>${rec.best?`<span class="chip green">${rec.best} кг</span>`:'<span class="chev">›</span>'}</div></button>`}
function recordsFor(n){const target=baseExerciseName(n).toLowerCase();let count=0,best=0;st.sessions.forEach(s=>s.ex.filter(e=>baseExerciseName(e.n).toLowerCase()===target).forEach(e=>e.set.filter(x=>x.ok).forEach(x=>{count++;best=Math.max(best,+x.w||0)})));return{count,best}}
function findExercise(token){const id=decodeURIComponent(token||'');if(id.startsWith('custom:')){const raw=id.slice(7),meta=inferCustomMeta(raw);return{id,n:displayExerciseName(raw),raw,...meta,custom:true}}if(id.startsWith('og:')){const rawId=id.slice(3),x=ogLibrary.find(e=>e.id===rawId);return x?{...x,id,rawId,custom:false}:null}return null}
function openExerciseDetail(token){const ex=findExercise(token);if(!ex)return toast('Упражнение не найдено');const best=bestEstimateFor(ex.raw||ex.n);rmState={id:ex.id,w:best?.w||20,r:best?.r||5};renderExerciseDetail(ex)}
function openExerciseDetailByName(token){const raw=decodeURIComponent(token||'');const ex={id:`custom:${raw}`,n:displayExerciseName(raw),raw,...inferCustomMeta(raw),custom:true};const best=bestEstimateFor(raw);rmState={id:ex.id,w:best?.w||20,r:best?.r||5};renderExerciseDetail(ex)}
