'use strict';
function instructionRu(ex){const i=ex?.instructions||{};return String(i.ru||i.russian||'').trim()}
function detailPlanKey(ex){return ex.custom?(ex.raw||ex.n):ruExerciseName(ex.n)}
function renderExerciseDetail(ex){
 const title=ex.custom?ex.n:ruExerciseName(ex.n),body=BP_RU[ex.bp]||ex.bp||'—',eq=ex.custom?(EQ_RU[ex.eq]||'Своё'):(EQ_RU[ex.eq]||ex.eq||'—'),target=ruTarget(ex.tg),sourceId=ex.rawId||ex.sourceId||null,key=detailPlanKey(ex),best=bestEstimateFor(key,sourceId),hist=historySetsFor(key,sourceId),rules=planOccurrences(key),est=estimate1RM(rmState.w,rmState.r),gif=mediaUrl(ex.gif||ex.gif_url||''),img=mediaUrl(ex.image||''),tech=instructionRu(ex),en=ex.sourceName||(!ex.custom?ex.n:'');
 if(best&&rmState.id===ex.id&&rmState.w===20&&rmState.r===5){rmState.w=best.w;rmState.r=best.r}
 const currentEst=estimate1RM(rmState.w,rmState.r);
 modal(`<div class="sheet-grabber"></div><div class="detail-title">${esc(title)}</div>${en&&String(en).toLowerCase()!==String(title).toLowerCase()?`<div class="detail-en">${esc(en)}</div>`:''}<div class="detail-tags"><span>${esc(body)}</span><span>${esc(eq)}</span><span>${esc(target)}</span></div>
  ${gif||img?`<div class="exercise-media"><img src="${gif||img}" alt="${esc(title)}" loading="eager"></div>`:''}
  <button class="add-plan-btn" onclick="addToPlanSheet('${encodeURIComponent(ex.id)}')">＋ Добавить в мой план</button>${ex.custom?`<div class="detail-actions"><button onclick="editExerciseAlias('${encodeURIComponent(ex.raw)}')">✎ Изменить</button><button class="danger-text" onclick="removeAddedExercise('${encodeURIComponent(ex.raw)}')">⌫ Удалить добавленные</button></div>`:''}
  ${tech?`<div class="section">ТЕХНИКА ВЫПОЛНЕНИЯ</div><div class="tech-card">${esc(tech)}</div>`:''}
  ${rules.length?`<div class="section">МОИ СЕТЫ И ПРАВИЛА</div><div class="rule-list">${rules.map(ruleCardHtml).join('')}</div>`:''}
  <div class="section">РАСЧЁТНЫЙ 1ПМ</div>${best?`<div class="history-best">Из журнала: <b>${best.est} кг</b> · ${best.w}×${best.r}${best.date?` · ${best.date}`:''}</div>`:''}<div class="rm-grid"><div><label>Вес (кг)</label><div class="stepbox"><button onclick="stepRM('w',-2.5)">−</button><b id="rmW">${fmt1(rmState.w)}</b><button onclick="stepRM('w',2.5)">＋</button></div></div><div><label>Повт.</label><div class="stepbox"><button onclick="stepRM('r',-1)">−</button><b id="rmR">${rmState.r}</b><button onclick="stepRM('r',1)">＋</button></div></div></div><div class="rm-est-row"><span>Оценка</span><b id="rmEst">${currentEst!==null?`${fmt1(currentEst)} кг`:'—'}</b></div><div class="muted rm-note">Формула Эпли · расчёт по одному подходу. Для >12 повторов оценку не показываем.</div>
  ${hist.length?`<div class="section">ПОСЛЕДНИЕ СЕТЫ</div>${hist.slice(0,8).map(h=>`<div class="history-row"><span>${esc(h.date)}</span><b>${h.w} кг × ${h.r}${h.rpe!==''?` @${h.rpe}`:''}</b></div>`).join('')}`:''}
  ${!ex.custom||gif||img?`<div class="source-note">Данные и техника: ExerciseDB dataset. Медиа © Gym visual; в публичном/коммерческом использовании нужны условия правообладателя. <a href="${OG_SOURCE_URL}" target="_blank" rel="noopener">Источник</a></div>`:''}`)
}
function fmt1(v){return Number(v)%1?Number(v).toFixed(1):String(Number(v))}
function estimate1RM(w,r){w=Number(w);r=Number(r);if(!Number.isFinite(w)||!Number.isFinite(r)||w<=0||r<1||r>12)return null;const v=r===1?w:w*(1+r/30);return Math.round(v*10)/10}
function stepRM(k,d){if(k==='w')rmState.w=Math.max(0,Math.round((Number(rmState.w)+d)*2)/2);else rmState.r=Math.max(1,Math.min(20,Math.round(Number(rmState.r)+d)));const est=estimate1RM(rmState.w,rmState.r);if($('#rmW'))$('#rmW').textContent=fmt1(rmState.w);if($('#rmR'))$('#rmR').textContent=rmState.r;if($('#rmEst'))$('#rmEst').textContent=est!==null?`${fmt1(est)} кг`:'—'}
function historySetsFor(n,sourceId=null){const target=baseExerciseName(n).toLowerCase(),out=[];[...st.sessions].reverse().forEach(s=>{[...s.ex].forEach(e=>{const nameMatch=baseExerciseName(e.n).toLowerCase()===target,sourceMatch=sourceId&&String(e.sourceId||'')===String(sourceId);if(!nameMatch&&!sourceMatch)return;[...e.set].reverse().forEach(x=>{if(x.ok&&x.w&&x.r)out.push({date:s.date,w:+x.w,r:+x.r,rpe:x.rpe??''})})})});return out}
function bestEstimateFor(n,sourceId=null){let best=null;historySetsFor(n,sourceId).forEach(x=>{const est=estimate1RM(x.w,x.r);if(est!==null&&(!best||est>best.est))best={...x,est}});return best}
function planOccurrences(n){const target=baseExerciseName(n).toLowerCase(),out=[];ROUTINES.forEach(r=>{const entries=routineEntries(r);groupIndexedEntries(entries).forEach(g=>{if(g.base.toLowerCase()===target)out.push({r,g})})});return out}
function ruleCardHtml(o){const{r,g}=o,type=methodType(g.entries),desc=formatPrescription(g.entries);return `<div class="rule-card"><div class="row between"><b>W${r.w} · ${esc(r.c)}</b>${type?`<span class="chip method-chip">${type}</span>`:''}</div><div class="rule-prescription">${esc(desc)}</div><div class="rule-meta">RPE ${RPE[r.w]} · темп ${esc(tempoOnly(r.p||''))} · ${esc(planRestRule(r,g))}</div></div>`}
function addToPlanSheet(token){const ex=findExercise(token);if(!ex)return;const planName=ex.custom?(ex.raw||ex.n):ruExerciseName(ex.n),source=ex.custom?'':(ex.rawId||ex.id.replace(/^og:/,''));modal(`<div class="sheet-grabber"></div><h2>Добавить в мой план</h2><div class="muted">${esc(planName)}</div><div class="rm-grid"><div class="field"><label>Неделя</label><select id="addWeek">${[1,2,3,4,5,6,7,8].map(w=>`<option value="${w}" ${w===st.week?'selected':''}>W${w}</option>`).join('')}</select></div><div class="field"><label>День</label><select id="addDay">${['A1','B','C','A2','D'].map(c=>`<option>${c}</option>`).join('')}</select></div></div><div class="rm-grid"><div class="field"><label>Подходы</label><input id="addSets" inputmode="numeric" value="3"></div><div class="field"><label>Повторы</label><input id="addReps" inputmode="numeric" value="10"></div></div><div class="field"><label>Вес, кг</label><input id="addWeight" inputmode="decimal" value="0"></div><div class="field"><label>Заметка / правило</label><input id="addNote" value="Добавлено из базы упражнений"></div><button class="btn primary full" onclick="saveAddedExercise('${encodeURIComponent(planName)}','${source}')">Добавить</button>`)}
function saveAddedExercise(token,source){const n=decodeURIComponent(token),w=+$('#addWeek').value,c=$('#addDay').value,sn=Math.max(1,+$('#addSets').value||3),r=Math.max(1,+$('#addReps').value||10),weight=Math.max(0,Number(String($('#addWeight').value).replace(',','.'))||0),d=$('#addNote').value||'';const key=`${w}-${c}`;(st.planAdds[key]||(st.planAdds[key]=[])).push({n,s:sn,r,w:weight,d,sourceId:source||null});save();closeModal();st.week=w;render();toast(`Добавлено: W${w} ${c}`)}
function editExerciseAlias(token){const raw=decodeURIComponent(token),current=st.aliases[raw]||raw;modal(`<div class="sheet-grabber"></div><h2>Изменить название</h2><div class="field"><label>Название</label><input id="aliasInput" value="${esc(current)}"></div><button class="btn primary full" onclick="saveExerciseAlias('${encodeURIComponent(raw)}')">Сохранить</button>`)}
function saveExerciseAlias(token){const raw=decodeURIComponent(token),v=$('#aliasInput').value.trim();if(!v)return;st.aliases[raw]=v;save();closeModal();render();toast('Название сохранено')}
function removeAddedExercise(token){const raw=decodeURIComponent(token);let n=0;Object.keys(st.planAdds||{}).forEach(k=>{const before=st.planAdds[k].length;st.planAdds[k]=st.planAdds[k].filter(e=>baseExerciseName(e.n)!==raw);n+=before-st.planAdds[k].length});save();closeModal();render();toast(n?`Удалено добавлений: ${n}`:'Основной цикл не удаляется')}
