'use strict';

if(!st.profileBio||typeof st.profileBio!=='object')st.profileBio={heightCm:null,birthDate:null,sex:null};

(()=>{const css=document.createElement('style');css.textContent=`
.profile-overview{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.profile-overview .metric{min-width:0}.profile-overview .metric b{font-size:22px}.profile-card-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.strength-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin-top:12px}.strength-summary .metric b{font-size:20px}.strength-list{display:flex;flex-direction:column}.strength-item{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:13px 0;border-bottom:1px solid #303034;background:transparent;border-left:0;border-right:0;border-top:0;width:100%;color:inherit;text-align:left}.strength-item:last-child{border-bottom:0}.strength-item-title{font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.strength-item-meta{color:#8e8e93;font-size:12px;margin-top:4px}.strength-delta{font-weight:800;font-variant-numeric:tabular-nums}.strength-delta.up{color:var(--green)}.strength-delta.down{color:#ff9f0a}.strength-chart{width:100%;height:auto;display:block;margin:12px 0 4px}.strength-history-row{display:grid;grid-template-columns:86px 1fr auto;gap:9px;align-items:center;padding:9px 0;border-bottom:1px solid #303034}.strength-history-row:last-child{border-bottom:0}.profile-edit-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.profile-edit-grid .field:last-child{grid-column:1/-1}.strength-empty{padding:18px;text-align:center;color:#8e8e93}.profile-cloud-note{margin-top:8px;color:#8e8e93;font-size:12px}
`;document.head.appendChild(css)})();

function profileAgeFromBirth(v){if(!v)return null;const d=new Date(v+'T12:00:00');if(Number.isNaN(d.getTime()))return null;const now=new Date();let a=now.getFullYear()-d.getFullYear();const m=now.getMonth()-d.getMonth();if(m<0||(m===0&&now.getDate()<d.getDate()))a--;return a>=0&&a<130?a:null}
function profileCurrentWeight(){const w=typeof latestW==='function'?latestW():null;return w==null?null:+w}
function profileHeightText(){const h=+st.profileBio.heightCm||0;return h?`${h} см`:'—'}
function profileAgeText(){const a=profileAgeFromBirth(st.profileBio.birthDate);return a==null?'—':`${a} лет`}
function profileWeightText(){const w=profileCurrentWeight();return w==null?'—':`${w} кг`}
function profileSexLabel(v){return v==='male'?'Мужской':v==='female'?'Женский':v==='other'?'Другой':'Не указан'}
function profileE1rm(w,r){w=+w||0;r=+r||0;if(!w||!r)return 0;if(typeof advE1rm==='function')return advE1rm(w,r);return r===1?w:w*(1+r/30)}

function profileExerciseSeries(){
 const map=new Map(),sessions=[...(st.sessions||[])].sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||(+a.started||0)-(+b.started||0));
 sessions.forEach(s=>{
  const perSession=new Map();
  (s.ex||[]).forEach(e=>{
   const base=typeof baseExerciseName==='function'?baseExerciseName(e.n):String(e.n||'').split(' — ')[0];
   const doneSets=(e.set||[]).filter(x=>x.ok&&(+x.w||0)>0&&(+x.r||0)>0);if(!doneSets.length)return;
   const key=base.toLowerCase();let z=perSession.get(key);if(!z){z={base,sets:[],sourceId:e.sourceId||null};perSession.set(key,z)}z.sets.push(...doneSets);
  });
  perSession.forEach((z,key)=>{
   const maxWeight=Math.max(...z.sets.map(x=>+x.w||0)),best5=Math.max(0,...z.sets.filter(x=>+x.r===5).map(x=>+x.w||0)),e1=Math.max(...z.sets.map(x=>profileE1rm(x.w,x.r))),volume=z.sets.reduce((a,x)=>a+(+x.w||0)*(+x.r||0),0);
   let rec=map.get(key);if(!rec){rec={key,base:z.base,sourceId:z.sourceId,points:[],sets:0};map.set(key,rec)}
   rec.points.push({date:s.date||'',started:+s.started||0,e1:+e1.toFixed(1),maxWeight:+maxWeight.toFixed(1),best5:+best5.toFixed(1),sets:z.sets.length,volume:Math.round(volume)});rec.sets+=z.sets.length;
  });
 });
 const out=[...map.values()].map(x=>{const p=x.points,first=p[0],last=p[p.length-1],best=Math.max(...p.map(z=>z.e1)),bestWeight=Math.max(...p.map(z=>z.maxWeight)),best5=Math.max(0,...p.map(z=>z.best5)),growth=first?.e1>0?((best-first.e1)/first.e1*100):0;return{...x,first,last,best:+best.toFixed(1),bestWeight,best5,growth:+growth.toFixed(1),workouts:p.length}});
 return out.sort((a,b)=>(b.last?.date||'').localeCompare(a.last?.date||'')||b.workouts-a.workouts)
}
function profileMedianGrowth(rows){const a=rows.filter(x=>x.workouts>=2&&x.growth>-50&&x.growth<250).map(x=>x.growth).sort((a,b)=>a-b);if(!a.length)return null;const m=Math.floor(a.length/2);return +(a.length%2?a[m]:(a[m-1]+a[m])/2).toFixed(1)}
function profileStrengthOverviewHtml(){const rows=profileExerciseSeries(),growth=profileMedianGrowth(rows),totalSets=rows.reduce((a,x)=>a+x.sets,0);return `<div class="card"><div class="row between"><div><div class="title">Силовой прогресс</div><div class="muted">Только упражнения, которые реально выполнялись</div></div><span class="chip green">${rows.length} упр.</span></div><div class="strength-summary"><div class="metric"><span>Упражнений</span><b>${rows.length}</b></div><div class="metric"><span>Рабочих сетов</span><b>${totalSets}</b></div><div class="metric"><span>Медианный рост 1ПМ</span><b>${growth==null?'—':`${growth>=0?'+':''}${growth}%`}</b></div></div>${rows.length?`<div class="strength-list">${rows.slice(0,30).map(profileStrengthRow).join('')}</div>`:'<div class="strength-empty">После завершённых тренировок здесь появятся графики роста силовых.</div>'}</div>`}
function profileStrengthRow(x){const latest=x.last?.e1||0,delta=x.growth||0;return `<button class="strength-item" onclick="openStrengthExercise('${encodeURIComponent(x.key)}')"><div><div class="strength-item-title">${esc(typeof displayExerciseName==='function'?displayExerciseName(x.base):x.base)}</div><div class="strength-item-meta">${x.workouts} трен. · лучший вес ${x.bestWeight} кг · 1ПМ сейчас ≈ ${latest} кг</div></div><div class="strength-delta ${delta>0?'up':delta<0?'down':''}">${delta>0?'+':''}${delta.toFixed(1)}%</div></button>`}
function profileStrengthChart(points,key='e1'){
 const vals=points.map(x=>+x[key]||0),w=330,h=125,pad=14,min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),dx=points.length>1?(w-pad*2)/(points.length-1):0;
 const pts=points.map((x,i)=>{const px=pad+i*dx,py=h-pad-((+x[key]||0)-min)/range*(h-pad*2);return[px,py]}),poly=pts.map(x=>x.join(',')).join(' ');
 return `<svg class="strength-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="График роста силовых"><line x1="${pad}" y1="${h-pad}" x2="${w-pad}" y2="${h-pad}" stroke="#343438"/><polyline points="${poly}" fill="none" stroke="var(--green)" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="${i===pts.length-1?5:3}" fill="var(--green)"/>`).join('')}</svg>`
}
function openStrengthExercise(token){const key=decodeURIComponent(token),x=profileExerciseSeries().find(z=>z.key===key);if(!x)return;const first=x.first?.e1||0,last=x.last?.e1||0,latestChange=first?((last-first)/first*100):0;modal(`<div class="sheet-grabber"></div><div class="row between"><div><h2>${esc(typeof displayExerciseName==='function'?displayExerciseName(x.base):x.base)}</h2><div class="muted">История силовых</div></div><button class="btn tiny" onclick="closeModal()">✕</button></div><div class="strength-summary"><div class="metric"><span>Лучший 1ПМ</span><b>${x.best} кг</b></div><div class="metric"><span>Лучший вес</span><b>${x.bestWeight} кг</b></div><div class="metric"><span>Рост к первой</span><b>${x.growth>=0?'+':''}${x.growth}%</b></div></div>${profileStrengthChart(x.points)}<div class="muted small">Первая оценка 1ПМ: ${first} кг · последняя: ${last} кг (${latestChange>=0?'+':''}${latestChange.toFixed(1)}%)</div><div class="section">ПО ТРЕНИРОВКАМ</div>${[...x.points].reverse().map(p=>`<div class="strength-history-row"><span class="muted small">${esc(p.date)}</span><span><b>1ПМ ≈ ${p.e1} кг</b><div class="muted small">${p.sets} сет. · объём ${p.volume.toLocaleString('ru-RU')} кг</div></span><b>${p.maxWeight} кг</b></div>`).join('')}`)}

function profileOverviewHtml(){const name=cloud?.profile?.display_name||'Профиль';return `<div class="card"><div class="profile-card-head"><div><div class="title">${esc(name)}</div><div class="muted">Профиль спортсмена</div></div><button class="btn tiny" onclick="profileEditSheet()">Изменить</button></div><div class="profile-overview"><div class="metric"><span>Рост</span><b>${profileHeightText()}</b></div><div class="metric"><span>Вес</span><b>${profileWeightText()}</b></div><div class="metric"><span>Возраст</span><b>${profileAgeText()}</b></div></div><div class="profile-cloud-note">Вес берётся из журнала веса. Рост и дата рождения сохраняются в профиле.</div></div>`}
function profileEditSheet(){const b=st.profileBio||{};modal(`<div class="sheet-grabber"></div><h2>Профиль спортсмена</h2><div class="profile-edit-grid"><div class="field"><label>Рост, см</label><input id="bioHeight" inputmode="decimal" type="number" min="100" max="250" step="0.5" value="${b.heightCm||''}" placeholder="Например, 183"></div><div class="field"><label>Дата рождения</label><input id="bioBirth" type="date" value="${esc(b.birthDate||'')}"></div><div class="field"><label>Пол</label><select id="bioSex"><option value="" ${!b.sex?'selected':''}>Не указан</option><option value="male" ${b.sex==='male'?'selected':''}>Мужской</option><option value="female" ${b.sex==='female'?'selected':''}>Женский</option><option value="other" ${b.sex==='other'?'selected':''}>Другой</option></select></div></div><div class="card"><div class="row between"><div><b>Текущий вес</b><div class="muted small">Записывается отдельно и строит собственный график</div></div><b>${profileWeightText()}</b></div></div><button class="btn primary full" onclick="profileSaveBio()">Сохранить</button>`)}
async function profileSaveBio(){const h=Number(String($('#bioHeight')?.value||'').replace(',','.'))||null,birth=$('#bioBirth')?.value||null,sex=$('#bioSex')?.value||null;if(h&&(h<100||h>250))return toast('Проверь рост');st.profileBio={heightCm:h,birthDate:birth,sex};save();if(window.cloud?.ready&&cloud.user){const r=await cloud.client.from('profiles').update({height_cm:h,birth_date:birth,sex,updated_at:new Date().toISOString()}).eq('id',cloud.user.id).select().single();if(r.data)cloud.profile={...(cloud.profile||{}),...r.data};if(r.error)console.warn('profile bio sync',r.error)}closeModal();statsPage();toast('Профиль сохранён')}

const _profileStatsPage=window.statsPage;
if(typeof _profileStatsPage==='function')window.statsPage=function(){const r=_profileStatsPage.apply(this,arguments),root=$('#stats');if(root){root.insertAdjacentHTML('afterbegin',profileOverviewHtml()+profileStrengthOverviewHtml())}return r};

let profileCloudHydrated=false;
async function profileHydrateCloud(){if(profileCloudHydrated||!window.cloud?.ready||!cloud.user)return;profileCloudHydrated=true;try{const r=await cloud.client.from('profiles').select('height_cm,birth_date,sex,display_name').eq('id',cloud.user.id).maybeSingle();if(r.data){const remote={heightCm:r.data.height_cm==null?null:+r.data.height_cm,birthDate:r.data.birth_date||null,sex:r.data.sex||null};const hasRemote=remote.heightCm||remote.birthDate||remote.sex;if(hasRemote){st.profileBio=remote;save()}else if(st.profileBio.heightCm||st.profileBio.birthDate||st.profileBio.sex){await cloud.client.from('profiles').update({height_cm:st.profileBio.heightCm||null,birth_date:st.profileBio.birthDate||null,sex:st.profileBio.sex||null,updated_at:new Date().toISOString()}).eq('id',cloud.user.id)}if(typeof statsPage==='function')statsPage()}}catch(e){console.warn('profile hydrate',e)}}
setInterval(profileHydrateCloud,1600);setTimeout(profileHydrateCloud,700);

function profileWrapTrainerDetail(){const f=window.trainerClientDetail;if(typeof f!=='function'||f.__profileStats)return;const base=f;const w=async function(id){const out=await base.apply(this,arguments);setTimeout(async()=>{try{if(!window.cloud?.user)return;const r=await cloud.client.from('profiles').select('height_cm,birth_date,sex').eq('id',id).maybeSingle();const sh=$('#sheet');if(!sh||!r.data)return;const a=profileAgeFromBirth(r.data.birth_date),h=r.data.height_cm;const block=document.createElement('div');block.className='card';block.innerHTML=`<div class="row between"><div><b>Профиль</b><div class="muted small">Рост · возраст</div></div><div style="text-align:right"><b>${h?`${h} см`:'—'} · ${a==null?'—':`${a} лет`}</b><div class="muted small">${profileSexLabel(r.data.sex)}</div></div></div>`;const metrics=sh.querySelector('.metrics');if(metrics)metrics.insertAdjacentElement('afterend',block);else sh.prepend(block)}catch(e){console.warn('client profile',e)}},0);return out};w.__profileStats=true;window.trainerClientDetail=w}
setInterval(profileWrapTrainerDetail,1800);setTimeout(profileWrapTrainerDetail,1000);

setTimeout(()=>{try{statsPage()}catch(e){}},120);
