'use strict';
function roundLoad(v,step=2.5){return Math.max(0,Math.round(Number(v||0)/step)*step)}
function progressionFor(name,target=8){const key=baseExerciseName(name).toLowerCase();const sessions=[...(st.sessions||[])].reverse();for(const s of sessions){const matches=(s.ex||[]).filter(e=>baseExerciseName(e.n).toLowerCase()===key);if(!matches.length)continue;const sets=matches.flatMap(e=>e.set||[]).filter(x=>x.ok&&Number(x.w)>0);if(!sets.length)continue;const rpes=sets.filter(x=>x.rpe!==''&&Number.isFinite(+x.rpe)).map(x=>+x.rpe);if(!rpes.length)return null;const avg=rpes.reduce((a,b)=>a+b,0)/rpes.length;const top=sets.reduce((a,b)=>Number(b.w)>Number(a.w)?b:a,sets[0]);let factor=1,label='Оставить вес';if(avg<=target-1.5){factor=1.05;label='+5%'}else if(avg<=target-.75){factor=1.025;label='+2,5%'}else if(avg>=target+1.5){factor=.95;label='−5%'}else if(avg>=target+.75){factor=.975;label='−2,5%'}const suggested=roundLoad(Number(top.w)*factor);return{from:Number(top.w),suggested,avg:Math.round(avg*10)/10,label,date:s.date}}
return null}
const _progressExerciseGroupCard=window.exerciseGroupCard;
if(typeof _progressExerciseGroupCard==='function')window.exerciseGroupCard=function(s,group){let html=_progressExerciseGroupCard(s,group);const p=progressionFor(group.base,s.target);if(!p)return html;const block=`<div class="auto-progression"><span>Автопрогрессия</span><b>${p.suggested} кг</b><small>${p.label} · прошлый ср. RPE ${p.avg}</small></div>`;const pos=html.lastIndexOf('</div>');return pos>=0?html.slice(0,pos)+block+html.slice(pos):html+block};
const _progressStartPage=window.startPage;
if(typeof _progressStartPage==='function')window.startPage=function(){_progressStartPage();if(st.current){const head=document.querySelector('#start .workout-head .row');if(head&&!head.querySelector('.focus-btn')){const b=document.createElement('button');b.className='btn tiny focus-btn';b.textContent='Фокус';b.onclick=openFocusMode;head.appendChild(b)}}};
function nextIncomplete(){if(!st.current)return null;for(let ei=0;ei<st.current.ex.length;ei++){const e=st.current.ex[ei];for(let si=0;si<e.set.length;si++)if(!e.set[si].ok)return{e,ei,x:e.set[si],si}}return null}
function openFocusMode(){const z=nextIncomplete();if(!z)return modal('<div class="sheet-grabber"></div><h2>Тренировка выполнена</h2><button class="btn primary full" onclick="finish()">Завершить</button>');const s=st.current,p=progressionFor(z.e.n,s.target),method=methodType?[methodType([{n:z.e.n}])]:'';modal(`<div class="sheet-grabber"></div><div class="focus-kicker">СЛЕДУЮЩИЙ ПОДХОД</div><div class="focus-ex">${esc(displayExerciseName(baseExerciseName(z.e.n)))}</div><div class="focus-count">Подход ${z.si+1} из ${z.e.set.length}</div><div class="focus-values"><div><span>Вес</span><b>${z.x.w||0} кг</b></div><div><span>Повторы</span><b>${z.x.r||'—'}</b></div><div><span>RPE</span><b>${s.target}</b></div></div>${p?`<div class="auto-progression focus-auto"><span>По прошлой тренировке</span><b>${p.suggested} кг</b><small>${p.label}</small></div>`:''}<button class="btn primary full focus-done" onclick="focusComplete(${z.ei},${z.si})">✓ Выполнено</button><button class="btn full" onclick="closeModal()">Вернуться к списку</button>`)}
function focusComplete(ei,si){if(!st.current)return;const e=st.current.ex[ei],x=e.set[si];x.ok=true;save();if(e.rest>0)timer(e.rest);closeModal();startPage();setTimeout(openFocusMode,250)}
