'use strict';
function trainerIsTrainer(){
 const email=String(cloud?.user?.email||'').trim().toLowerCase();
 return email==='butafutsiy@mail.ru'||cloud?.profile?.role==='trainer'||(typeof window.unvrslTrainerMode==='function'&&window.unvrslTrainerMode())
}
function refreshTrainerNav(){
 let page=$('#clients');if(!page){page=document.createElement('section');page.id='clients';page.className='page';document.querySelector('main')?.appendChild(page)}
 let btn=document.querySelector('.nav button[data-p="clients"]');
 if(trainerIsTrainer()&&!btn){btn=document.createElement('button');btn.dataset.p='clients';btn.innerHTML='<span class="ico">◉</span>Клиенты';btn.addEventListener('click',()=>nav('clients'));document.querySelector('.nav')?.appendChild(btn)}
 if(btn)btn.style.display=trainerIsTrainer()?'block':'none';
 const navEl=document.querySelector('.nav');if(navEl)navEl.style.gridTemplateColumns=`repeat(${trainerIsTrainer()?6:5},1fr)`;
 if(trainerIsTrainer())clientsPage();
}
function trainerSnapshot(){return{kind:'unvrsl-plan',schema:1,title:'UNVRSL FIT · 8 недель',createdAt:new Date().toISOString(),weeks:8,routines:ROUTINES.map(r=>({w:r.w,c:r.c,t:r.t,p:r.p||'',e:routineEntries(r).map(e=>({...e}))}))}}
async function clientsPage(){
 const el=$('#clients');if(!el)return;if(!trainerIsTrainer()){el.innerHTML='<div class="card"><div class="title">Режим тренера выключен</div></div>';return}
 el.innerHTML=`<div class="card"><div class="row between"><div><div class="title">Клиенты</div><div class="muted">Планы, тренировки и прогресс</div></div><button class="btn primary tiny" onclick="trainerShareCurrent()">＋ План</button></div></div><div id="clientMetrics" class="metrics"><div class="metric"><span>Клиентов</span><b>—</b></div><div class="metric"><span>Тренировок 7 дней</span><b>—</b></div></div><div id="clientList"><div class="card muted">Загружаю…</div></div><button class="btn full" onclick="trainerPlansSheet()">Мои отправленные планы</button>`;
 if(!cloud.ready||!cloud.user){$('#clientList').innerHTML='<div class="card muted">Войди в аккаунт, чтобы видеть клиентов.</div>';return}
 const {data:rels,error}=await cloud.client.from('trainer_clients').select('*').eq('trainer_id',cloud.user.id).neq('status','archived');if(error){$('#clientList').innerHTML=`<div class="card muted">${esc(error.message)}</div>`;return}
 const ids=(rels||[]).map(x=>x.client_id);let profiles=[];if(ids.length){const r=await cloud.client.from('profiles').select('id,display_name').in('id',ids);profiles=r.data||[]}
 const since=new Date(Date.now()-7*86400000).toISOString().slice(0,10);let recent=[];if(ids.length){const r=await cloud.client.from('workouts').select('user_id,workout_date,avg_rpe,completed_sets,total_sets,payload').in('user_id',ids).gte('workout_date',since).order('workout_date',{ascending:false});recent=r.data||[]}
 const metrics=$('#clientMetrics');if(metrics)metrics.innerHTML=`<div class="metric"><span>Клиентов</span><b>${ids.length}</b></div><div class="metric"><span>Тренировок 7 дней</span><b>${recent.length}</b></div>`;
 const list=$('#clientList');if(!ids.length){list.innerHTML='<div class="card"><div class="title">Пока нет клиентов</div><div class="muted" style="margin-top:6px">Отправь программу по ссылке. После принятия клиент появится здесь.</div><button class="btn primary full" onclick="trainerShareCurrent()">Отправить программу</button></div>';return}
 list.innerHTML=ids.map(id=>{const p=profiles.find(x=>x.id===id),rw=recent.filter(x=>x.user_id===id),last=rw[0],high=rw.some(x=>Number(x.avg_rpe)>=9.5);return `<button class="card exlib-btn client-card" onclick="trainerClientDetail('${id}')"><div class="row between"><div class="grow"><b>${esc(p?.display_name||'Клиент')}</b><div class="catalog-meta">${last?`Последняя: ${esc(last.workout_date)} · RPE ${last.avg_rpe??'—'}`:'Нет тренировок за 7 дней'}</div></div>${high?'<span class="chip orange">Высокий RPE</span>':'<span class="chev">›</span>'}</div></button>`}).join('')
}
async function trainerShareCurrent(){
 if(!cloudConfigured())return cloudSetupSheet();if(!cloud.user)return cloudAccountSheet();if(!trainerIsTrainer())return alert('В аккаунте включи роль «Тренер».');
 const title=prompt('Название программы','UNVRSL FIT · 8 недель');if(!title)return;const snapshot=trainerSnapshot();snapshot.title=title;toast('Создаю ссылку…');
 const p=await cloud.client.from('plans').insert({trainer_id:cloud.user.id,title,version:1,snapshot}).select().single();if(p.error)return alert(p.error.message);await cloud.client.from('plan_versions').insert({plan_id:p.data.id,trainer_id:cloud.user.id,version:1,snapshot});
 const token=(crypto.randomUUID?.()||('t'+Date.now()+Math.random())).replaceAll('-','');const inv=await cloud.client.from('plan_invites').insert({token,trainer_id:cloud.user.id,plan_id:p.data.id,max_uses:1}).select().single();if(inv.error)return alert(inv.error.message);const link=`${location.origin}${location.pathname}?invite=${encodeURIComponent(token)}`;trainerShareSheet(title,link)
}
function trainerShareSheet(title,link){modal(`<div class="sheet-grabber"></div><h2>Программа готова</h2><div class="muted">${esc(title)}</div><div class="share-link">${esc(link)}</div><button class="btn primary full" onclick="trainerCopyLink('${encodeURIComponent(link)}')">Скопировать ссылку</button>${navigator.share?`<button class="btn full" onclick="navigator.share({title:'UNVRSL FIT',url:'${link}'})">Поделиться</button>`:''}`)}
async function trainerCopyLink(token){const link=decodeURIComponent(token);try{await navigator.clipboard.writeText(link);toast('Ссылка скопирована')}catch(e){prompt('Скопируй ссылку',link)}}
async function trainerClientDetail(id){
 if(!cloud.user)return;const pr=await cloud.client.from('profiles').select('id,display_name').eq('id',id).maybeSingle();const wr=await cloud.client.from('workouts').select('*').eq('user_id',id).order('workout_date',{ascending:false}).limit(12);const bw=await cloud.client.from('bodyweights').select('*').eq('user_id',id).order('measure_date',{ascending:false}).limit(8);const ar=await cloud.client.from('plan_assignments').select('plan_id,version,status,assigned_at,plans(title)').eq('client_id',id).eq('trainer_id',cloud.user.id);
 const workouts=wr.data||[],weights=bw.data||[],assign=ar.data||[],avg=workouts.length?Math.round(workouts.filter(x=>x.avg_rpe!=null).reduce((a,x)=>a+Number(x.avg_rpe||0),0)/Math.max(1,workouts.filter(x=>x.avg_rpe!=null).length)*10)/10:null;
 modal(`<div class="sheet-grabber"></div><div class="detail-title">${esc(pr.data?.display_name||'Клиент')}</div><div class="metrics"><div class="metric"><span>Тренировок</span><b>${workouts.length}</b></div><div class="metric"><span>Средний RPE</span><b>${avg??'—'}</b></div></div>${weights.length?`<div class="section">ВЕС</div><div class="rule-card"><b>${weights[0].weight_kg} кг</b><div class="muted small">${esc(weights[0].measure_date)}</div></div>`:''}${assign.length?`<div class="section">ПРОГРАММА</div>${assign.map(a=>`<div class="rule-card"><b>${esc(a.plans?.title||'Программа')} · v${a.version}</b><div class="muted small">${esc(a.status)}</div></div>`).join('')}`:''}<div class="section">ПОСЛЕДНИЕ ТРЕНИРОВКИ</div>${workouts.length?workouts.map(w=>`<div class="history-row"><span>${esc(w.workout_date)}</span><b>${esc(w.payload?.c||'')}${w.avg_rpe!=null?` · RPE ${w.avg_rpe}`:''}</b></div>`).join(''):'<div class="muted">Пока нет данных.</div>'}`)
}
async function trainerPlansSheet(){
 if(!cloud.user)return cloudAccountSheet();const r=await cloud.client.from('plans').select('id,title,version,created_at,is_active').eq('trainer_id',cloud.user.id).order('created_at',{ascending:false});if(r.error)return alert(r.error.message);modal(`<div class="sheet-grabber"></div><div class="row between"><h2>Мои планы</h2><button class="btn tiny primary" onclick="trainerShareCurrent()">＋</button></div>${(r.data||[]).length?(r.data||[]).map(p=>`<div class="listline"><div class="row between"><div><b>${esc(p.title)}</b><div class="muted small">Версия ${p.version}</div></div><button class="btn tiny" onclick="trainerNewInvite('${p.id}','${encodeURIComponent(p.title)}')">Ссылка</button></div></div>`).join(''):'<div class="muted">Планов пока нет.</div>'}`)
}
async function trainerNewInvite(planId,titleToken){const token=(crypto.randomUUID?.()||('t'+Date.now()+Math.random())).replaceAll('-','');const r=await cloud.client.from('plan_invites').insert({token,trainer_id:cloud.user.id,plan_id:planId,max_uses:1}).select().single();if(r.error)return alert(r.error.message);trainerShareSheet(decodeURIComponent(titleToken),`${location.origin}${location.pathname}?invite=${token}`)}
function remotePlansHtml(){const plans=Array.isArray(st.remotePlans)?st.remotePlans:[];if(!plans.length)return'';return `<div class="section">ПРОГРАММЫ ТРЕНЕРА</div>${plans.map(p=>`<div class="card routine remote-plan"><div class="row between"><div><h3>${esc(p.title)}</h3><div class="muted">${esc(p.trainer||'Тренер')} · версия ${p.version||1}</div></div><button class="btn tiny primary" onclick="openRemotePlan('${p.id}')">Открыть</button></div></div>`).join('')}`}
const _trainerPlanPage=window.planPage;
if(typeof _trainerPlanPage==='function')window.planPage=function(){_trainerPlanPage();const el=$('#plan');if(el&&Array.isArray(st.remotePlans)&&st.remotePlans.length)el.insertAdjacentHTML('afterbegin',remotePlansHtml())};
function openRemotePlan(id){const p=(st.remotePlans||[]).find(x=>x.id===id);if(!p)return;const routines=p.snapshot?.routines||[];const weeks=[...new Set(routines.map(r=>r.w))].sort((a,b)=>a-b);modal(`<div class="sheet-grabber"></div><div class="detail-title">${esc(p.title)}</div><div class="muted">Тренер: ${esc(p.trainer||'—')}</div>${weeks.map(w=>`<div class="section">НЕДЕЛЯ ${w}</div>${routines.filter(r=>r.w===w).map((r,i)=>{const idx=routines.indexOf(r);return `<div class="listline row between"><div><b>${esc(r.c)} · ${esc(r.t)}</b><div class="muted small">${esc(r.p||'')}</div></div><button class="btn tiny primary" onclick="beginRemotePlan('${id}',${idx})">Старт</button></div>`}).join('')}`).join('')}`)}
function beginRemotePlan(id,index){const p=(st.remotePlans||[]).find(x=>x.id===id),r=p?.snapshot?.routines?.[index];if(!r)return;const entries=r.e||[];st.current={id:'remote-'+Date.now(),date:iso(),w:r.w||0,c:r.c||'План',name:r.t||p.title,target:RPE[r.w]||8,tempo:r.p||'',started:Date.now(),ended:null,planId:p.id,trainerId:p.trainerId||null,ex:entries.map((e,i)=>({n:e.n,d:e.d||'',rest:typeof rest==='function'?rest(r,e,i):(e.rest||90),g:e.g||null,sourceId:e.sourceId||null,mode:e.m?'cardio':'reps',set:Array.from({length:e.s||1},(_,j)=>e.m?{n:j+1,min:Number(e.m||0),rpe:'',ok:false}:{n:j+1,w:Number(e.w||0),r:Number(e.r||0),rpe:'',ok:false})}))};save();closeModal();nav('start')}
setTimeout(()=>{refreshTrainerNav();render()},50);
