'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const api=require('../intake-engine'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(require.resolve('../exercise-catalog.js'),'utf8'),ctx);const catalog=ctx.window.UNVRSL_EXERCISES;
const answer=(extra={})=>({name:'Семён',age:25,goal:'muscle',experience:'regular',days:3,minutes:75,limitations:false,equipment:Object.keys(api.EQUIPMENT),excluded:[],...extra});
const sets=p=>p.weeks.map(w=>w.days.map(d=>d.ex.reduce((s,e)=>s+e.sets.length,0)));
test('focus and format survive sharing; old answers get neutral defaults',()=>{const a=answer({focus:['core','arms'],format:'varied'});assert.deepEqual(api.decode(api.encode(a)).focus,a.focus);assert.equal(api.decode(api.encode(a)).format,'varied');assert.deepEqual(api.validate(answer()).focus,[]);assert.equal(api.validate(answer()).format,'balanced');for(const extra of [{focus:['chest','legs','arms']},{focus:['arms','arms']},{focus:['unknown']},{format:'unknown'}])assert.throws(()=>api.validate(answer(extra)))});
test('focus includes available target movement without removing basic movements',()=>{const r=api.generate(answer({focus:['core']}),catalog);assert.ok(r.program);for(const d of r.program.weeks[0].days){assert.ok(d.ex.some(e=>e.sourceId==='0276'));assert.ok(d.ex.some(e=>e.bp==='chest'));assert.ok(d.ex.some(e=>e.bp==='back'));assert.ok(d.ex.some(e=>e.bp==='upper legs'))}assert.match(r.rationale.join(' '),/Кор/)});
test('formats redistribute the same set budget while all weights stay unset',()=>{const balanced=api.generate(answer(),catalog).program;for(const format of ['concentrated','varied']){const p=api.generate(answer({format}),catalog).program;assert.deepEqual(sets(p),sets(balanced));assert.ok(p.weeks[0].days.some((d,i)=>d.ex.length!==balanced.weeks[0].days[i].ex.length));for(const d of p.weeks.flatMap(w=>w.days)){assert.equal(new Set(d.ex.map(e=>e.sourceId)).size,d.ex.length);assert.ok(d.ex.every(e=>e.sets.length>=1&&e.sets.length<=4&&e.sets.every(s=>s.w===null)))}}});
test('focused formats respect equipment, exclusions and manual restriction routing',()=>{for(const days of [2,3,4])for(const format of Object.keys(api.FORMATS))for(const focus of [[],['back'],['chest','arms'],['legs','core']]){const r=api.generate(answer({days,format,focus,equipment:['dumbbells'],excluded:['canon:lateral_raise']}),catalog);if(!r.program){assert.ok(r.issues.length);assert.equal(api.generate(answer({days,equipment:['dumbbells'],excluded:['canon:lateral_raise']}),catalog).program,null);continue}for(const e of r.program.weeks.flatMap(w=>w.days.flatMap(d=>d.ex))){assert.ok(['dumbbell','body weight'].includes(e.eq));assert.notEqual(e.sourceId,'canon:lateral_raise')}assert.equal(api.generate(answer({focus,format,limitations:true}),catalog).program,null)}});

test('focus and format keep original basic movements and upper/lower split',()=>{for(const days of [3,4])for(const focus of [['core'],['arms','shoulders'],['legs']])for(const format of Object.keys(api.FORMATS)){const base=api.generate(answer({days}),catalog).program, p=api.generate(answer({days,focus,format}),catalog).program;for(let di=0;di<days;di++){const expected=base.weeks[0].days[di].ex.slice(0,4).map(e=>e.sourceId),actual=p.weeks[0].days[di].ex;for(const id of expected)assert.ok(actual.some(e=>e.sourceId===id),`${days}/${focus}/${format}/${di}: ${id}`);if(days===4&&di%2)assert.ok(actual.every(e=>!['chest','back','upper arms','shoulders'].includes(e.bp)));}}});
