const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = (name) => fs.readFileSync(path.join(root, name), "utf8");

test("light theme is selectable, applied, persisted, and included in PWA shell cache", () => {
  const html = read("index.html"), app = read("app.js"), sw = read("sw.js"), css = read("theme-light.css");
  assert.match(html, /theme-light\.css\?v=412/);
  assert.match(app, /function setTheme\(theme\)/);
  assert.match(app, /document\.documentElement\.dataset\.theme=theme/);
  assert.match(app, /onclick="setTheme\('light'\)"/);
  assert.match(app, /onclick="setTheme\('dark'\)"/);
  assert.doesNotMatch(fs.readFileSync(path.join(root, "og-settings.js"), "utf8"), /<button disabled>☀ Светлая<\/button>/);
  assert.match(app, /function setTheme\(theme\)[^\n]*closeModal\(\)/);
  assert.doesNotMatch(app, /function setTheme\(theme\)[^\n]*(?:settingsSheet\(\)|render\(\))/);
  assert.match(fs.readFileSync(path.join(root, "og-settings.js"), "utf8"), /canonicalSettingsSheet=window\.settingsSheet/);
  assert.match(app, /#gear'\)\.addEventListener\('click',\(\)=>settingsSheet\(\)\)/);
  assert.doesNotMatch(read("cloud-patch.js"), /stopImmediatePropagation|cloudSettingsSheet/);
  assert.match(css, /html\[data-theme="light"\]/);
  assert.match(css, /html\[data-theme="light"\] body \.nav\{background:[^}]+!important/);
  assert.match(css, /html\[data-theme="light"\] body \.search,[\s\S]*?background:#fff!important;color:#19191d!important/);
  assert.match(css, /html\[data-theme="light"\] body\{background:#f3f4f6!important;color:#19191d!important\}/);
  assert.match(css, /html\[data-theme="light"\] body \.brand\{color:#19191d!important\}/);
  assert.match(css, /html\[data-theme="light"\] body \.filterchip\.on\{background:[^}]+!important/);
  assert.match(css, /html\[data-theme="light"\] body \.card,[\s\S]*?background-image:none!important/);
  assert.match(css, /html\[data-theme="light"\] body \.star-btn\{background:#eceef2!important/);
  assert.match(sw, /<link rel="stylesheet" href="\(\[\^"\]\+\)"/);
});
